### ISSUE TITLE
Selfies encoder adds spurious nitrogen to molecule

### ISSUE THREAD

**Issue by TheGoldstone** [aspuru-guzik-group/selfies#102]
Dear maintainers,

I encountered an issue working with an implementation of the STONED algorithm based on the selfies package. The selfies encoder seems to add nitrogen tokens to the SELFIES string, although the passed smiles string only consists of carbon atoms.
Here is what I could boil the problem down to:
```python
import selfies

sml = 'C(=C(C)C(C)(C)C)C'
slf = selfies.encoder(sml)
print(slf)
```
prints this string, with a nitrogen token in the third position:
`[C][=Branch1][=N][=C][Branch1][C][C][C][Branch1][C][C][Branch1][C][C][C][C]`

Interestingly, if this string is decoded back to SMILES with the decoder, the original molecule without nitrogen is recreated. It is only after the molecule is manipulated by the STONED algorithm that nitrogen remains in the SMILES string after the decoding.

I've encountered this problem with several hydrocarbons, but have not been able to discover an underlying pattern. I've also checked the validity of the SMILES string in this example with the rdkit.Chem.SanitizeMol function.

Thank you very much, I look forward to hearing from you.

**Comment by MarioKrenn6240** [comment]
Thanks for this comment. In your string, [=N] is used as a number which defines the length of the branch (see the branch symbol before). That is explained further in Table III, and Chapter II.D in our [code paper](https://arxiv.org/abs/2302.03620).

It seems to be an illdefined behaviour of STONED, so i suggest to directly ask in the [selfies-stoned](https://github.com/aspuru-guzik-group/stoned-selfies) github.

**Comment by LiorZ** [comment]
On a similar topic, the following SMILES 
`NC1=NC=NC2=C1N=CN2[C@@H]1O[C@H](COP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]1O` is encoded to 

`[N][C][=N][C][=N][C][=C][Ring1][=Branch1][N][=C][N][Ring1][Branch1][C@@H1][O][C@H1][Branch2][Ring1][Ring1][C][O][P][=Branch1][C][=O][Branch1][C][O-1][O][P][=Branch1][C][=O][Branch1][C][O-1][O-1][C@@H1][Branch1][C][O][C@H1][Ring1]**[S]**[O]`

Why is there an S here? there's no sulfur in the molecule

**Comment by akshat998** [comment]
Hi @LiorZ, 
The character after a [Ring] encodes a number. [S] is indicating the size of the ring -- this is a feature of SELFIES where characters are overloaded. So, [S] is not a sulfur.
Regards
Akshat

**Comment by LiorZ** [comment]
Got it, thanks!
