### ISSUE TITLE
Represent Ring-Couplings

### ISSUE THREAD

**Issue by wolnikla** [aspuru-guzik-group/selfies#103]
The molecules i generate only have ortho-couplings, when i represent them using RDKit. That means the branch continues at the direct neighbour of the start atom from the ring. Is there any way to define where the branch continues after the ring is closed, for example getting meta and para-couplings from a benzene ring.

**Comment by robpollice** [comment]
Could you elaborate your question? I am not sure I understand it correctly.

**Comment by wolnikla** [comment]
So i think i found an answer by myself for my question. But this leads me to another question. So my question in the first place was the following: If we have a SELFIES-String like this: [C][C][C][C][C][C][C][C][Ring1][#Branch1][C][C][C][C]. Then the string will represent to a 6 membered ring with two carbon chains coupled to it. The Ring symbol will create a bond between the first preceding carbon and the 6th preceding carbon right. But before that the carbon chain will be created. so in such a case we will always have a ortho coupling. My question was, how you can represent another coupling so that the chain will not continue directly next to where it goes in the ring. The solution is to create a new branch "inside" of the ring(means between the first preceding and the 6th preceding atom). What i now observed is: If i create a new branch inside of a ring, the atoms that come behind the created branch and should belong to the "main-branch" getting added to the end of the branch, which was created inside of the ring.

**Comment by wolnikla** [comment]
Quick example: [C][C][C][C][C][C][Branch1][Branch1][C][C][Ring1][=Branch1][C][C][C][C][C][C][C] This SELFIES String will create a molecule with a 6 membered ring and two chains connected with the ring (Surprisingly this gives me an output of a molecule with 14 carbons and not with 15 carbons). One chain has 2 carbons and the other has 6. For my understanding there have to be 3 chains that will be connected to the ring: Two 2 membered chains next to each other (ortho) and on 5 membered chain with one/two ring atoms between (para/meta) but thats not the case

**Comment by robpollice** [comment]
The SMILES I get back for this SELFIES is 'CCC1CCC(CC1)CCCCCCC', which has 15 carbon atoms. I do not understand why you think you should have three chains. Could you elaborate on that?

**Comment by wolnikla** [comment]
I got 14 carbon atoms for my xyz coordinates, but that could also be a mistake of RDKit. My problem was that i thought the branch length will the following atoms as part of the branch but Mario told me that the length stands for the following symbols including branch, ring and index symbols. So i tried another SELFIES String and i got the expected 3D structure and the expected SMILES String. Thank you for your effort in trying to help me!
