### ISSUE TITLE
Preserving the dot symbol (".") in the alphabet

### ISSUE THREAD

**Issue by vandrw** [aspuru-guzik-group/selfies#104]
Hi! The current version of the library provides the `get_alphabet_from_selfies` function that generates a list of symbols from an iterable. However, if one uses the returned alphabet to generate an encoding (as seen below), the script would raise an error that there is no symbol "." in the alphabet.

```
sf.selfies_to_encoding(
        selfies_string,
        vocab_stoi=symbol_to_index_dict,
        pad_to_len=16,
        enc_type="label",
)
```

After having a closer look at the functions involved, there are two possible solutions:
1. Preserve the dot symbol in the alphabet by removing the following line:
https://github.com/aspuru-guzik-group/selfies/blob/120b776b14b6d7ff1508de37aba6571d24121176/selfies/utils/selfies_utils.py#L71
3. Clean up the dot symbol from the char_list created here (i.e., `char_list.remove(".")`):
https://github.com/aspuru-guzik-group/selfies/blob/120b776b14b6d7ff1508de37aba6571d24121176/selfies/utils/encoding_utils.py#L50

In the context of training a machine learning model, would this symbol provide vital information? If so, wouldn't it be better to preserve it in the alphabet?

**Comment by MarioKrenn6240** [comment]
Hi @vandrw -- Thanks for your interest. The dot is used to represent two unconnected molecules, or unphysical bonds that cannot be represented in a native way within SMILES (Ferrocenes). For generative models, we didnt encounter any usecase of it yet. We only introduced it to be able to read even some il-formed SMILES. Hope this helps!
