### ISSUE TITLE
Random SELFIES

### ISSUE THREAD

**Issue by lhallee** [aspuru-guzik-group/selfies#108]
Hello!

Great work! I heard that every combination of SELFIES tokens is a valid molecule. Is this true, and does that mean shuffling them is always valid?
Best,
- Logan

**Comment by akshat998** [comment]
Hello, 

Yes -- that is correct. We make use of the fast in: 
* STONED-SELFES: https://github.com/aspuru-guzik-group/stoned-selfies for producing diverse sets of molecules & 
* JANUS: https://github.com/aspuru-guzik-group/JANUS for optimizing properties

Regards
Akshat

**Comment by lhallee** [comment]
Thanks so much!

**Comment by DawnJYe** [comment]
> Thanks so much!

I'm feel sorry to bother you.All combinations are valid？
