### ISSUE TITLE
About conversion from A 2 B back2 A

### ISSUE THREAD

**Issue by tszslovewanpu** [aspuru-guzik-group/selfies#109]
smiles1---->selfies1
selfies1---->smiles2
smiles2---->selfies1

The "selfies" library exhibits biases in the conversion between SMILES and SELFIES formats. This is specifically manifested as follows:

A SMILES string, denoted as SMILES1, is converted by the library to a SELFIES string, denoted as SELFIES1.
This SELFIES1 is then converted back by the library to a SMILES string, denoted as SMILES2.
Upon converting SMILES2 back to the SELFIES format using the library, it results again in SELFIES1.

The same SELFIES representation corresponds to two distinct SMILES strings

For example:

smiles1: my data
CC(C)(c1ccc2c(c1)B1c3ccc(N4c5ccccc5C(C)(C)c5ccccc54)cc3Oc3cccc(c31)O2)c1ccc2c(c1)B1c3ccc(N4c5ccccc5C(C)(C)c5ccccc54)cc3Oc3cccc(c31)O2

selfies1:
[C][C][Branch1][C][C][Branch2][=Branch1][Ring2][C][=C][C][=C][C][=Branch1][Ring2][=C][Ring1][=Branch1][B][C][=C][C][=C][Branch2][Ring1][O][N][C][=C][C][=C][C][=C][Ring1][=Branch1][C][Branch1][C][C][Branch1][C][C][C][=C][C][=C][C][=C][Ring1][=Branch1][Ring1][S][C][=C][Ring2][Ring1][=Branch1][O][C][=C][C][=C][C][=Branch1][#Branch1][=C][Ring1][=Branch1][Ring2][Ring1][=C][O][Ring2][Ring2][C][C][=C][C][=C][C][=Branch1][Ring2][=C][Ring1][=Branch1][B][C][=C][C][=C][Branch2][Ring1][O][N][C][=C][C][=C][C][=C][Ring1][=Branch1][C][Branch1][C][C][Branch1][C][C][C][=C][C][=C][C][=C][Ring1][=Branch1][Ring1][S][C][=C][Ring2][Ring1][=Branch1][O][C][=C][C][=C][C][=Branch1][#Branch1][=C][Ring1][=Branch1][Ring2][Ring1][=C][O][Ring2][Ring2][C]

smiles2:
CC(C)(C1=CC=C2C(=C1)B3C4=CC=C(N5C6=CC=CC=C6C(C)(C)C7=CC=CC=C75)C=C4OC8=CC=CC(=C83)O2)C9=CC=C%10C(=C9)B%11C%12=CC=C(N%13C%14=CC=CC=C%14C(C)(C)C%15=CC=CC=C%15%13)C=C%12OC%16=CC=CC(=C%16%11)O%10

What are the difference between smiles1 and smiles2?

Thanks!

**Comment by MarioKrenn6240** [comment]
Thanks for your message. SELFIES de-aromatizes the representation such that 100% robustness can be guaranteed. This is explained in [https://pubs.rsc.org/en/content/articlelanding/2023/DD/D3DD00044C](our 2023 code paper) in detail. Beside of that, the two molecules you plot are the same. You can check [https://www.leruli.com](LERULI) to plot them and will observe that they give the same structure.

**Comment by tszslovewanpu** [comment]
Thank you very much, great work!
