### ISSUE TITLE
Are your selfies similar to DeepSmiles, but are batter than DeepSmiles? 

### ISSUE THREAD

**Issue by xuzhang5788** [aspuru-guzik-group/selfies#11]
https://github.com/baoilleach/deepsmiles

Thanks

**Comment by MarioKrenn6240** [comment]
Both DeepSmiles and SELFIES are string-based representations of molecules that improve the validity of Weininger's original SMILES -- in particular for generative tasks. SELFIES are more complex (underlying grammar, DeepSMILES has clever replacement rules of SMILES) and are 100% robust in all cases, see our paper: https://arxiv.org/abs/1905.13741
