### ISSUE TITLE
Fail to transform SMILES to SELFIES

### ISSUE THREAD

**Issue by tszslovewanpu** [aspuru-guzik-group/selfies#113]
Hello, and great job!
The following two smiles can't be transformed to SELFIES, can you help me?
O=N(=O)C1=CC=CN1         this is the GDB9 standard SMILES molecule from QM9 dataset
O=N(=O)c1ccc[nH]1             this is the relaxed geometry form SMILES, also from QM9 dataset
Thank you!

**Comment by MarioKrenn6240** [comment]
The error message reads:

`EncoderError: input violates the currently-set semantic constraints SMILES: O=N(=O)C1=CC=CN1. Errors: [N with 5 bond(s) - a max. of 3 bond(s) was specified]`

In your molecule, there is an nitrogen atom with 5 bonds. The standard SELFIES constraints bound the nitrogen to 3 bonds.

You can use this:
````
import selfies as sf
sf.encoder('O=N(=O)C1=CC=CN1', strict=False) # '[O][=N][=Branch1][C][=O][C][=C][C][=C][N][Ring1][Branch1]'
````

**Comment by tszslovewanpu** [comment]
Nice! Kind of you~
