### ISSUE TITLE
Error in SELFIES conversion when a sulfur is connected to an aromatic carbon

### ISSUE THREAD

**Issue by KunhuanLiu** [aspuru-guzik-group/selfies#114]
Hi,

We recently found that some SMILES string representations that contain sulfur bonded to an aromatic carbon will not be properly converted to SELFIES.  Example molecules are:
`[O-]C(=O)c1cc(CSc2nc3c([nH]2)cccc3)cc(c1)C(=O)[O-]`
`[O-]C(=O)c1cc(Sc2cc(cc(c2)C(=O)[O-])C(=O)[O-])cc(c1)C(=O)[O-] `
Both 2D structures look legitimate in ChemDraw.

I suspect that the program is recognizing "Sc" as the metal element.

**Comment by MarioKrenn6240** [comment]
I am using the following code:
````
import selfies as sf

m1='[O-]C(=O)c1cc(CSc2nc3c([nH]2)cccc3)cc(c1)C(=O)[O-]'
m2='[O-]C(=O)c1cc(Sc2cc(cc(c2)C(=O)[O-])C(=O)[O-])cc(c1)C(=O)[O-]'

sm1 = sf.encoder(m1)
sm2 = sf.encoder(m2)


msm1=sf.decoder(sm1)
msm2=sf.decoder(sm2)
````

It gives me two molecules that look the same to me. If you dont agree, can you please point to your issue more directly? What happens when you translate? What is the output and what is the code that does so? Thanks. 
<img width="976" alt="mol1" src="https://github.com/aspuru-guzik-group/selfies/assets/46604014/b21fbd7a-ceec-4f21-bb5f-0a0c5a0d8d55">

**Comment by KunhuanLiu** [comment]
Dear @MarioKrenn6240 ,
Thank you for attending to this issue and patience.  
I used the newest SELFIES to test these cases myself.  I confirm that I am not replicating the described error, which was observed in some internal data not generated by myself.  My apologies on not having a double check myself before submitting the ticket, and please feel free to close the ticket (or delete it, whichever is more appropriate).

Sincerely,

**Comment by MarioKrenn6240** [comment]
Thanks. Indeed your dataset might have been generated by an older version, and we have since fixed that issue. Good luck with your project!

**Comment by MarioKrenn6240** [comment]
OK
