### ISSUE TITLE
SELFIES decoding for some tokens

### ISSUE THREAD

**Issue by Olabisi-Aishat-Bello** [aspuru-guzik-group/selfies#118]
Hi!

I had a question regarding the smiles decoding for certain combinations of tokens. Using sf.decoder("[Ring1][Branch2]") or sf.decoder("[Branch2][#Branch3]") leads to simply empty SMILES strings. Does that mean there has to be an atom token present for every SELFIES string to be decoded into a valid molecule?

**Comment by robpollice** [comment]
Hi!
Thank you for your question. The short answer is yes. From a fundamental perspective, molecules consist of atoms, that is the presence of at least a single atom is a necessary condition for a valid molecule. Hence, when there is any molecular string representation, be it SMILES or SELFIES or similar, that does not contain a single atom, this representation does not correspond to a valid molecule. If you considered a hypothetical SMILES string "11", this would also be empty, that is not a valid molecule. Whether this is actually a valid SMILES string is a different question, in my opinion not, but SMILES explorer actually accepts it and gives an output. I hope this answers your question.

**Comment by Olabisi-Aishat-Bello** [comment]
Thank you! It does!
