### ISSUE TITLE
Model SELFIES VAE

### ISSUE THREAD

**Issue by KatynaSada** [aspuru-guzik-group/selfies#121]
Hi, do you have the trained SELFIES VAE available for download somewhere?

**Comment by MarioKrenn6240** [comment]
Hi @KatynaSada, we dont have the trained version, but the code is [here](https://github.com/aspuru-guzik-group/selfies/tree/master/examples/vae_example), and training it on QM9 is very quick on a standard laptop just on CPU.

**Comment by KatynaSada** [comment]
Thanks!! I thought it would require many resources to train, but I was easily able to train it. Another question, have you obtained good results training the model with the ZINC-250k drugs dataset (I noticed you also had that dataset)???

**Comment by MarioKrenn6240** [comment]
For larger molecules, i think VAEs are not the best options. I would recommend you to have a look at the [STONED algorithm](https://github.com/aspuru-guzik-group/stoned-selfies) based on SELFIES, or an extended representation that handles groups efficiently ([group selfies](https://github.com/aspuru-guzik-group/group-selfies)). In general we discuss various extensions and applications a lot in this [community review](https://www.cell.com/patterns/fulltext/S2666-3899(22)00206-9).
