### ISSUE TITLE
Two dataset links in README not working

### ISSUE THREAD

**Issue by robpollice** [aspuru-guzik-group/selfies#124]
The README links to two of the datasets used in the tests (MoleculeNet, eMolecules) do not work anymore.

**Comment by MarioKrenn6240** [comment]
Thanks Robert. For MoleculeNet, I think the new link is [this](https://moleculenet.org/datasets-1), i changed the link. Do you know the new location for the eMolecules Database? thanks!

**Comment by robpollice** [comment]
The new location is [https://downloads.emolecules.com/free/2024-12-01/](here) but I think this is not the same database that was available before.
