### ISSUE TITLE
Inconsistency with example in README

### ISSUE THREAD

**Issue by hmkim** [aspuru-guzik-group/selfies#23]
Via pip, I can't use the functions in "utils.py".
so, I imported it directly.

Could you check my installed version of selfies correctly?

<img width="801" alt="스크린샷 2020-08-20 오후 5 25 14" src="https://user-images.githubusercontent.com/4966343/90741293-1d5c7c80-e30a-11ea-959a-1b64491ee6d7.png">

**Comment by alstonlo** [comment]
Hi hmkim, 

Judging on the code outputs you provide, I believe you are running an older version of `selfies`. This is likely why you cannot use the functions in `utils.py`, as these functions only exist in `selfies v1.0.0`.

Could you please double check if `selfies v1.0.0` was installed (you can check by running `pip show selfies` in the console)? If an older version was installed instead, you can upgrade it by running `pip install selfies --upgrade`. 

Please let me know if this fixes the issue. Thanks!

**Comment by hmkim** [comment]
$ pip freeze | grep selfies
selfies==0.2.4

With this command, selfies could not be updated. 
$ pip install selfies --upgrade

**Comment by hmkim** [comment]
$ git clone https://github.com/aspuru-guzik-group/selfies.git
$ cd selfies
$ pip install .
Processing /root/selfies
ERROR: Package 'selfies' requires a different Python: 3.6.9 not in '>=3.7'
WARNING: You are using pip version 19.3.1; however, version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

My Python version is 3.6.9. Is any method with this python version?

**Comment by alstonlo** [comment]
That may be the issue, as `selfies` requires Python >= 3.7. 

Is it possible to try installing `selfies` again but with a different version of Python? Thanks!

**Comment by alstonlo** [comment]
In a few days, we will be releasing `selfies v1.0.1`, which will support Python >= 3.5. If you are interested in using `selfies` with python 3.6.9 specifically, I can keep you updated on this thread.

**Comment by hmkim** [comment]
In Python 3.6.x, 
I modified this python file 'kekulize.py'.
(because there is no function : from __future__ import annotations)


[kekulize.py.zip](https://github.com/aspuru-guzik-group/selfies/files/5120855/kekulize.py.zip)

**Comment by MarioKrenn6240** [comment]
SELFIES runs now with python 3.5+. Thanks for raising the issue.
