### ISSUE TITLE
One-hot encoding functions

### ISSUE THREAD

**Issue by ncfrey** [aspuru-guzik-group/selfies#27]
The functions for [one-hot encoding](https://github.com/aspuru-guzik-group/selfies/blob/master/examples/vae_example/data_loader.py) SELFIES strings found are really helpful, and I think it might be useful to clean them up and include them in `selfies.utils` or in a new `selfies.data_loader` module.  Some functions to reverse the encodings would be great too. I'm happy to give that a shot and open a PR if there's interest.

**Comment by MarioKrenn6240** [comment]
Hi Nathan! Thanks for reaching out. I like your suggestion of having a function to translate selfies from and to one-hot encoding per default. As you are an expert in the field of deep learning and chemistry, i would be happy to get your suggested PR. utils.py sounds good to me, then they can be used per default with pip installation of selfies, and we add these functionalities to the docs.

Let me know if you have any questions, or further suggestions!
Mario

**Comment by ncfrey** [comment]
Great! I will put something together for review. And thanks very much for your excellent work developing SELFIES! I've only just started using SELFIES, but the formalism is really interesting and the applications in other fields like quantum optical experiments are exciting.

**Comment by ncfrey** [comment]
Closed by #29

**Comment by MarioKrenn6240** [comment]
Thank you. We will announce this addition in selfie 1.0.2 (which will involve two more bug fixes in the next few days). Please feel free to suggest further functionalities that might be useful.
