### ISSUE TITLE
Regarding of  None from smiles

### ISSUE THREAD

**Issue by hmkim** [aspuru-guzik-group/selfies#28]
Hi there!

CC(C)(C)C1=CC(=C/C=C/c2cc(C(C)(C)C)[te+]c(C(C)(C)C)c2)C=C(C(C)(C)C)[Se]1
CC(C)(C)C1=CC(=C/C=C/c2cc(C(C)(C)C)[te+]c(C(C)(C)C)c2)C=C(C(C)(C)C)O1
CC(C)(C)C1=CC(=C/C=C/c2cc(C(C)(C)C)[te+]c(C(C)(C)C)c2)C=C(C(C)(C)C)[Te]1
CN(C)c1ccc(-c2cc(-c3ccc(N(C)C)cc3)[te+]c(-c3ccc(N(C)C)cc3)c2)cc1
CCc1nc#cn1CC1CC(c2ccccc2)(c2ccccc2)C(=O)O1
CN(C)c1ccc(-c2cc(-c3ccccc3)[te+]c(-c3ccc(N(C)C)cc3)c2)cc1
CN(C)c1ccc(-c2cc(-c3ccccc3)[te+]c(-c3ccc(N)cc3)c2)cc1
O=C(NCCCCN1CCN(c2cccc(Cl)c2Cl)CC1)c1cc2ccccc2[te]1
COc1ccccc1N1CCN(CCCCNC(=O)c2cc3ccccc3[te]2)CC1
CN(C)c1ccc(-c2cc(-c3ccc(N)cc3)[te+]c(-c3ccc(N4CCOCC4)cc3)c2)cc1
CN(C)c1ccc(-c2cc(-c3ccc(N)cc3)[te+]c(-c3ccc(N)cc3)c2)cc1
Nc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(N4CCOCC4)cc3)[te+]2)cc1
Nc1ccc(-c2cc(-c3ccc(N4CCOCC4)cc3)cc(-c3ccc(N4CCOCC4)cc3)[te+]2)cc1
Nc1ccc(-c2cc(-c3ccc(N4CCOCC4)cc3)cc(-c3ccc(N)cc3)[te+]2)cc1

With these (smiles format), I can't get the selfies's result from smiles.

Could you check this issue, please?

**Comment by alstonlo** [comment]
Hi hmkim, 

The reason these inputs fail is because they have an aromatic Te. When writing the kekulization algorithm for SELFIES, we considered the Daylight (https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html) and OpenSMILES (http://opensmiles.org/opensmiles.html) specifications, both of which do not accept Te as an aromatic symbol. However, I now see that RDKit has an aromaticity extension that supports aromatic Te (https://www.rdkit.org/docs/RDKit_Book.html#id2); thus, we will add support for aromatic Te in `selfies v1.0.2`! 

Are you aware of any other aromatic symbols that are occasionally used?  Currently, we support the aromatic symbols `b, c, n, o, p, s, as, se`. Thank you for the bug reports, and for helping improve the `selfies` library!

**Comment by hmkim** [comment]
Hi  @alstonlo,

Thanks for your reply. 
It is my pleasure to get an opportunity to contribute.

and then
In this case, what is the cause of the problem?

> CCc1nc#cn1CC1CC(c2ccccc2)(c2ccccc2)C(=O)O1
i'm not familiar with chemical string format.

**Comment by alstonlo** [comment]
Sorry, I missed this example. The issue with this SMILES is the triple bond between aromatic carbons `(c#c)`, which our current algorithm cannot properly kekulize. I will look further into supporting such SMILES in `selfies v1.0.2`.

In the meanwhile, to encode the SMILES you provide, one solution to first kekulize them using RDKit (https://www.rdkit.org/docs/GettingStartedInPython.html#writing-molecules). The Kekulized SMILES can then be encoded without any error. Thanks!

**Comment by MarioKrenn6240** [comment]
Thank you hmkim, this issues have been fixed in v1.0.2. Thanks for the bug report!

**Comment by HelloJocelynLu** [comment]
Hi there, 
I'm excited to try the SELFIES, wonderful!
I found the same issue. I got None for molecule:
Encoding error 'C[Si](C)(C)Oc1cccc(F)[si]1[Si](C)(C)C': unrecognized aromatic symbol '[si]'.
Will this be fixed in the future?
Many thanks!

**Comment by MarioKrenn6240** [comment]
Hi  HelloJocelynLu! Thanks for your comment.

Aromatic Si is not officially supported by OpenSMILES, however it is supported by RDKit. We discussed this issue with a chemist, who explained that aromatic Si is usually very unstable, which might be the reason that it is not supported by the official SMILES definitions. As there seem to be no negative consequences, we decided to support it too. Have you encountered any other aromatic atoms that are not supported? Could you please push your changes to the main repo?

Thank you!
Mario

**Comment by HelloJocelynLu** [comment]
Hi Mario,
Thank you for you quick reply. I was parsing molecules from pubchem database.
(Source: https://2019-ncovgroup.github.io/data/)
After going though all molecules, another element I have found is 'Al'. I have pulled a request #37  also updated some molecules that involved in this issue as well.
Best,
Jocelyn

**Comment by MarioKrenn6240** [comment]
Thanks HelloJocelynLu, you modification is now in the repo, and in SELFIES v1.0.3.
