### ISSUE TITLE
When using sf.encoder to encode something that contains *, [(R6)n], [(Rc)p], [alkyl], [(CH2)n], etc., it will not be resolved and an error will be reported.

### ISSUE THREAD

**Issue by miracle1111111** [aspuru-guzik-group/selfies#30]
Although I can skip it, smiles like this make up a large part of my data set. The following are some examples of smiles that cannot be encoded:
C1=CC2=C(C(=CC(=C2)C(N3C4=NC(=NC(=C4N=N3)[R2])[R1])([R4])[R3])[(R6)n])N=C1
C(C(=[Z])C1[(CH2)n]N(C2=[M]C(=[L]C(=[K]2)N([R6a])[R5a])[Y])[(CH2)n]1)[(C)m](C3[(CH2)n]C([(R1)x])[(CH2)n]3)([R3])[R2]
C1CC2C(c(cC1N2C(=O)N3C4=C(C(=C(C(=C4[R1a])[R1b])[R1c])[R1d])[F,Cl,Br,I]C(C3[(R2a)p])[(R2b)r])[R4])[R3]
C1=C(C=C(C(=C1)N2C=C(C3=C(C=C(C=C32)[(Ra)m])O)[(Rb)n])[(Rc)p])O
C1=CC(=C2C(=C1Br)C=C(N2)[(Rb)n])[(Ra)m]
C1=C(C=C(C(=C1)[F,Cl,Br,I])[(Rc)p])O
CN1C(C[*][(CH2)n]C1[Ra])[Rb]
C(C[F,Cl,Br,I])C[*]CC1C(C(CC1([R1])[R2])([R3])[R4])[Y]C(C([R7])([R8])[Z])([R5])[R6]
CC(C)S(=O)(=O)C(C[R4])[(CH2)n]C1=CC(=C(C=C1)[R5])[R6]
C1=CC(=C(C=C1[(CH2)n]C(C[R4])S(=O)(=O)NC2=NC(=C([R1])S2)[R2])[R6])[R5]
C1=CC(=C(C=C1[(CH2)n]C(C[R4])C(=O)NC2=NC3=C(N=C(C=C3)[R3])S2)[R6])[R5]
CC(C)C1=CC=CC(=N1)[(R5)n]
CC(C)C1=NC=NC(=N1)[(R5)n]
CC(C)C1[(CH2)p]CC(C[(CH2)q]1)N([R])[*][R][B]
CC(C)N1[(CH2)p]CN(C[(CH2)q]1)[R][*]
CC(C)N1[(CH2)r]CC2([(CH2)s]CN([(CH2)q]2)[R][*])[(CH2)p]1
C1=C(N=C(N)N=C1)N2[(CH2)p]C3C([(CH2)v]2)[(CH2)q]N([(CH2)t]3)[R][*]
C1=C([R2])[X5][X4][X3]2[X1](cn[X2]12)C3[(CH2)n]C([R1])[(CH2)n]3
C1=CN2C(=CN=C2C=C1[R2])C3[(CH2)n]C([R1])[(CH2)n]3
C1=C([R2])[X5][X4][X3]2[X1](cn[X2]12)C3[(CH2)n]C(N)[(CH2)n]3
C1CN(C(CN1C2CN(C2)C(=O)[Z])[(R1)s])C(=O)[Y]
C(=C\1/C(=O)N([R2])[Y][F,Cl,Br,I]1)(/C2=[Z6][Z7]=C([Z5]2)[*])\[R3]
C(=C\1/C(=O)N(C(=[Q])[F,Cl,Br,I]1)[R2])(/C2=[Z1]C(=[Z4][Z3]=[Z2]2)[*])\[R3]
C1=C(C=C(C=C1/C(=C/2\C(=O)N(C(=[Q])[F,Cl,Br,I]2)[R2])/[R3])[*])[R1]
C(=C\1/C(=O)N(C(=[Q])[F,Cl,Br,I]1)[R2])(/C2=[Z6][Z7]=C([Z5]2)[*])\[R3]
C1=C(/C(=C/2\C(=O)N(C(=[Q])[F,Cl,Br,I]2)[R2])/[R3])OC(=C1[R1])[*]
C(=C\1/C(=O)N(C(=[Q])[F,Cl,Br,I]1)[R2])(/C2=[Z10]C(=[Z9][Z8]2)[*])\[R3]
C1=C(/C(=C/2\C(=O)N(C(=[Q])[F,Cl,Br,I]2)[R2])/[R3])SC(=C1[*])[R1]
C1(=C(C2=[D3][D2](=[D1]([L1])[*]=B2)[(R3)n])[F,Cl,Br,I]C(=C1[R2])C3=[Y][Z]=[D6]([L2])[D5]=[D4]3[(R4)q])[R1]
C1=C(C2=C(C(=C(C3=[Y][Z]=C(C=C3[(R4)q])[L2])[F,Cl,Br,I]2)[R2])[R1])B=[*]C(=C1[(R3)n])[L1]
133it [00:00, 1223.44it/s]
C1(=C(C2=[D3]([(R3)n])[D2]=[D1][*](=B2)[L1])SC(=C1[R2])C3=[Y][Z](=[D6][D5](=[D4]3)[(R4)q])[L2])[R1]
C1=C(C(=N[Z](=C1)[L2])C2=C(C(=C(C3=C(C=C([L1])[*]=N3)[(R3)n])S2)[R1])[R2])[(R4)q]
CC1cc[(CH2)n]OC1C
Cc1c(CCNC(=O)[R1b])C2=C(C=CC3=C2[Ea][(CH2)n]O3)[X']1
C=[CH]C1CC(C(C1)[M3][M2][M1][Y]([Z])[F,Cl,Br,I])[(CH)n]=C
[R4][(Ph)a][*][H][R3]
c1cc(ccc1/C=C/[R3a])c2ccc(cc2)[alkyl]
c1c([H][(H)r][R0])cc(c(c1[Y1])[X0])[Y2]
c1c(cc(c(c1F)C(F)(F)Oc2cc(c(c(c2)[Y1])[X0])F)[Y2])[B][*][R0]
c1c([H][H][alkenyl])cc(c(c1[Y1])[X0])[Y2]
C[C@H](C/C=C/C(=C/[C@H](C(=O)[C@@H](C)[C@@H]([C@@H](C)C/C(=C/C(=O)O)/C)O)[R9])/C)/C=C(\C=C\[C@H]1[C@](C=CC(=O)O1)([Ra])[R'])/[a]
[XH][Y][(Z)n]SS[(Z)n][Y][XH]
NO[(CH2)n][Y]
C1=CC(=C(C(=C1[F,Cl,Br,I])C2=C(C(=NN(C2=O)[B])[*])O[G])[Z])[Y]
C1=C(C=[F,Cl,Br,I]N(C1=O)C2=C(C=C3C4=C(C5N(C(C4)[R4])[(CH2)r]5)N(C3=[Z]2)[R1])[(R5)s])[L]B([R14])([R13])[R15]
C1=C(C=[F,Cl,Br,I]N(C1=O)C2=CC(=C3C4=C(CC5N(C4[R4])[(CH2)r]5)N(C3=[Z]2)[R1])[(R5)s])[L]B([R14])([R13])[R15]
C1C([(CH2)p]CN1[Q][B][*])[*]
C1COCC(CC2=C[3H]C3=C2C(=[V]C(=[*]3)[R23])[R24])N1C(=S)N
C1(=C(O)[*]=C([R24])[V]=C1[R23])I
205it [00:00, 995.69it/s] 
C1C(CN2C([R2])[(CH2)m][*](C([R3])[(CH2)n]2)[K]C3=[F,Cl,Br,I]C=[*]C4=[V]C=C([R1])[U]=C34)OC(=O)N1[G]
C1=C([R1])[U]=C2C(=[F,Cl,Br,I]C=[*]C2=[V]1)[L1]
C1=C([R1])[U]=C2C(=[F,Cl,Br,I]C=[*]C2=[V]1)N
C(C1=[F,Cl,Br,I]C=[*]C2=[V]C=C([R1])[U]=C12)[L4]
C1=CC(=CC(=C1)[(R19)w])C(=O)NC2=C(NN=C2C(=O)NC3CCN(CC3[(R11)r])[R14a])[R2]
C1=Nc2c(C(=N1)[X1][*])n[*]c2[R2]
C1=CC=C(C=C1)[Zf]OC2=CC=C(C=C2)N(C3=NC=Nc4c3n[*]c4[R2f])[R3f]
C1CC2=CC3=C(C(=NC=N3)[X1][*])N2C1
C1CCC2=CC3=C(C(=NC=N3)[X1][*])N2CC1
C1CN2C3=C(C=[*]2)N=CN=C3N1[Y1][*]
C1=C(N(C2=C1N=CN=C2[X1][*])[R2])[R1]
C1=C2C(=NN1[R2])C(=NC=N2)[X1][*]
CC(C)C1=NN2C(=C1)[*]2
CC(C)C12=CNN=C1[*]2
C=C1C(N(C(=[*])N1[Het])[R1])([R2])[R3]
C1=CC(=CC(=C1)B(C2=CC(=CC=C2)[(R2)n])O)[(R2)n]
CC1=C2C(=C(C)S1)[Y][*]O2
c1cc2(C(=O)C3=C([C@]4([C@]([H])([C@@H](C(=C(C4=O)C(=O)N)O)[R5])C(C3C(c2(cc1[(R7)n])[R8])([R2])[R1])([R3])[R4])O)O)[R6]
C12=C(C(=C3C(=C1[R7])[(X)n]3)[R7])C([C@]4([H])C(=C([C@]5([C@]([H])([C@@H](C(=C(C5=O)C(=O)N)O)[R5])C4([R3])[R4])O)O)C2=O)([R2])[R1]
C1=CC(=C2C(=C1[(Ra)m])C=C(C(=N2)[(Rb)n])[F,Cl,Br,I][Ar])[R]
C1=C2C(=C(C(=C1)[(RIII)n])[B]N([R]I)[R]I)N=C(C(=C2[R][V])S(=O)(=O)[*])[R]I
C1(N([R4])[*]C([R])[(CH2)p]1)[(R6)q]
C([R])([R2])[*]N([R3])[R4]
C1=CC(=C2C=C(C(=NC2=C1C([R2])([R1])[*]N([R3])[R4])[(Rb)n])[F,Cl,Br,I][Ar])[(Ra)m]
C1=CC(=C2C(=C1[(Ra)m])C=C(C(=N2)[(Rb)n])S(=O)(=O)[Ar])[R]
C1=CC(=C2C(=C1[(Ra)m])C=C(C[Ar])C(=N2)[(Rb)n])[R]
C1=CC(=C2C=C(C(=NC2=C1C3CC(N(C3)[R4])[(R6)q])[(Rb)n])S(=O)(=O)[Ar])[(Ra)m]
C1CC(C2=C3C(=C(C=C2)[(Ra)m])C=C(C(=N3)[(Rb)n])S(=O)(=O)[Ar])C(CN(C1)[R4])[(R6)q]
CC(C)(C)[(C)s](N1C(=O)[Q1]([R4])[Q2]([R5])[(CH2)r]1)([R3a])[R3b]
C1(=C(C(=C2C(C(C(C(N12)[R3])[R4])[R5])[R6])[R7])[R2])C(=O)C(=O)N([R8])[(A1)n][L1][R1]
C1COCC(N1C2=NC3=C(C(=N2)C4=C([2H]=B[*]=C4[R3])[R4])N=C(N3[F,Cl,Br,I][R2])[R1])[(R2)k]
C1COCCN1C2=NC3=C(C(=N2)C4=C(C(=C5C(=C4[R3])NC(=N5)[(R11)n])[R7])[R4])N=C(N3[F,Cl,Br,I][R2])[R1]
C1=CC(=CC(=C1)CN2C=NC3=C2N=C(N=C3C4=CC=CC(=C4)O)N5CCOCC5)[(R13)p]
C[(CH2)n]N1CC[F,Cl,Br,I](CC1)([R4])[R5]
C[(CH2)n]N1C2CCC1CC(C2)C3=CC=CC=C3
C[C@@]1(CC[Z][(CH2)p]1)[R8]
CC1CC2C(C(C)C3(CCC4C5CC[C@@]6([H])CC(=O)CCC6(C)C5CC4=C(C)[(CH2)n]3)O2)N(C1)[R30]
C1=C(C=C(C2=C1N=C(N2[L1][Ar1])[Ra])[Rm])[(L2)n][Ar2]

thank you for your reply！

**Comment by MarioKrenn6240** [comment]
Dear miracle1111111,
Thank you for reporting these examples. As far as I see, all of the problematic examples involve wildcards, placeholders or similar symbols. So far, SELFIES does not support them, as we mention in the [ReadTheDocs](https://selfies.readthedocs.io/en/latest/selfies.html#standard-functions).

However, potentially there are simple ways to add them, in a non-semantically robust way. Let me discuss this topic with my colleages and we come back to you.

Thanks again for reporting this,
Mario

**Comment by alstonlo** [comment]
Hi @miracle1111111, 

It appears that the strings you list are actually [SMARTS](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html) and not valid SMILES. Symbols such as `[(R6)n], [(Rc)p], [alkyl], [(CH2)n]` do not exist in SMILES; and although the symbol `*` does exist in SMILES (the wildcard symbol), we currently do not support it (as stated in the documentation). To be certain that these are not SMILES, may I ask where you obtained the dataset?

Thanks!

**Comment by miracle1111111** [comment]
Hello, some of them are collected in the literature, such as the following picture, which is a screenshot of the molecular picture in the literature.，C1=CC2=C(C(=CC(=C2)C(N3C4=NC(=NC(=C4N=N3)[R2])[R1])([R4])[R3])[(R6)n])N=C1&nbsp;


In addition, I have a question to ask you. Do you think it will be helpful to replace smiles with selfies in the task of using deep learning to identify molecular structure diagrams into molecular formula smiles?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "alstonlo"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 下午4:26
收件人: "aspuru-guzik-group/selfies"<selfies@noreply.github.com&gt;; 
抄送: "Miracle"<541766011@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [aspuru-guzik-group/selfies] When using sf.encoder to encode something that contains *, [(R6)n], [(Rc)p], [alkyl], [(CH2)n], etc., it will not be resolved and an error will be reported. (#30)





 
Hi @miracle1111111,
 
It appears that the strings you list are actually SMARTS and not valid SMILES. Symbols such as [(R6)n], [(Rc)p], [alkyl], [(CH2)n] do not exist in SMILES; and although the symbol * does exist in SMILES (the wildcard symbol), we currently do not support it (as stated in the documentation). To be certain that these are not SMILES, may I ask where you obtained the dataset?
 
Thanks!

**Comment by miracle1111111** [comment]
Hello, some of them are collected in the literature, such as the following picture, which is a screenshot of the molecular picture in the literature.，C1=CC2=C(C(=CC(=C2)C(N3C4=NC(=NC(=C4N=N3)[R2])[R1])([R4])[R3])[(R6)n])N=C1
![2](https://user-images.githubusercontent.com/49110370/93194899-2e6aa300-f77b-11ea-81a0-bc2e3c0f5cec.png)
In addition, I have a question to ask you. Do you think it will be helpful to replace smiles with selfies in the task of using deep learning to identify molecular structure diagrams into molecular formula smiles?

**Comment by MarioKrenn6240** [comment]
Thank you for the comments. These strings are not true SMILES strings (for instance, RDKit doesnt recognize them), and SELFIES doesnt, at the moment, support them. However, we will add them in a systematic way in a non-semantically constrained way in one of the next versions. Thank you for the suggestion.
