### ISSUE TITLE
upgraded selfies?

### ISSUE THREAD

**Issue by woodg07** [aspuru-guzik-group/selfies#31]
Has there been a redefinition on how selfies get generated in the last month or so? My old code that uses this fails a bunch of assertion tests: 

e.g. an aromatic benzene (c1ccccc1) smiles used to be converted to [c][c][c][c][c][c][Ring1][Branch1_1] and is now converted to kekule benzene: [C][=C][C][=C][C][=C][Ring1][Branch1_2]

Thanks for the info

**Comment by MarioKrenn6240** [comment]
Hi Geoffrey,
Thanks for your message. Yes indeed there was a major update, from 0.x.x to 1.x.x recently -- see the [changelog at 17.08.2020](https://github.com/aspuru-guzik-group/selfies/blob/master/CHANGELOG.md). It included several conceptual modifications, for instance, as you mention, explicitly deals with aromatic rings in a semantically correct way by de-aromatizing them.

If you dont want to upgrade (for instance dont want to translate datasets again or retrain models), no problem you can continue with 0.2.4, it worked fine (just slower and had few small issues that needed to be solved at a fundamental level).

Hope this helps!
Mario
