### ISSUE TITLE
is selfies supporting stereochemistry, polyvalency, aromaticity, isotopic substitution... now?

### ISSUE THREAD

**Issue by 5AGE-zhang** [aspuru-guzik-group/selfies#38]
Hi, Dear MarioKrenn6240:

I have read your paper about selfies and I find it useful.
You stated in your paper that the selfies did not support stereochemistry, polyvalency, aromaticity, isotopic substitution and other special cases?
I wonder if selfies fixes these problems now?

**Comment by MarioKrenn6240** [comment]
Hi 5AGE-zhang,
Yes we have extended the code a lot after the paper.  In particular we can handle now all that SMILES can handle, most of it in a 100% symantically valid way. See the changelog for version 1.0.0:
https://github.com/aspuru-guzik-group/selfies/blob/master/CHANGELOG.md

If you encounter any properties that are not implemented, please let us know.

Thanks,
Mario

**Comment by 5AGE-zhang** [comment]
> 
> 
> Hi 5AGE-zhang,
> Yes we have extended the code a lot after the paper. In particular we can handle now all that SMILES can handle, most of it in a 100% symantically valid way. See the changelog for version 1.0.0:
> https://github.com/aspuru-guzik-group/selfies/blob/master/CHANGELOG.md
> 
> If you encounter any properties that are not implemented, please let us know.
> 
> Thanks,
> Mario

ok, thanks for your help! :)
