### ISSUE TITLE
SELFIES that can't be parsed by RDKit

### ISSUE THREAD

**Issue by skinnider** [aspuru-guzik-group/selfies#40]
Hi Mario,
Here is a list of the invalid SELFIES from our recent [preprint](https://chemrxiv.org/articles/preprint/Deep_Generative_Models_Enable_Navigation_in_Sparsely_Populated_Chemical_Space/13638347) as you requested. Among the ~220m SELFIES we generated there seem to have been 22,387 that couldn't be parsed for one reason or another.
I hope it wasn't something wrong on my end. Just to be sure, here is the code I used to identify invalid SELFIES: 

```
smiles = decoder(selfies)
mol = Chem.MolFromSmiles(str(smiles))
if mol is None:
        raise ValueError("invalid SELFIES: " + str(smiles))
```
Hope this is helpful.
[invalid-SELFIES.txt](https://github.com/aspuru-guzik-group/selfies/files/5929743/invalid-SELFIES.txt)

**Comment by MarioKrenn6240** [comment]
Hi Michael,
thanks a lot, we will look into it shortly. A quick question: i see that in most (all?) lines, there is a `<PAD>`. Are you removing this symbol before you send it into the `decoder`? 

For padding, you can use the `[nop]` symbol (see [here](https://github.com/aspuru-guzik-group/selfies#integer-and-one-hot-encoding-selfies)for an example).

Thanks!

**Comment by skinnider** [comment]
Hi Mario, you’re absolutely right, all of these are just cases where the generative model wasn’t able to learn where to place the padding token. I apologize for overlooking the existence of the ’no operation’ token within SELFIES itself - I just checked, and if I replace my own padding token with the `[nop]` symbol, then all of the 22,387 “invalid” SELFIES are successfully parsed. So that is a 100% validity rate over 220m structures… very impressive! 
I will replace the padding tokens with `[nop]` for all of the SELFIES outputs and update our analyses.
Sorry for the false alarm!

**Comment by MarioKrenn6240** [comment]
Glad we were able to resolve this. Thanks for reporting. Please let comments and suggestions comming! :)
