### ISSUE TITLE
Question regarding the output of selfies

### ISSUE THREAD

**Issue by Wentao-Shi** [aspuru-guzik-group/selfies#42]
Hello, 

I have a question regarding the output selfies. I trained an simple teacher-forced RNN based on selfies of molecules. My trained model generates selfies like the example below:
```
 [C][=S@@expl][=SHexpl][=P][/S+expl][/C@@Hexpl][/P@@expl][\Siexpl][C][C][C][/I][IH2expl]<sos>[C][SnH2expl][Sn+expl][=S@@expl][\S][#N+expl][=I][\I][C][C@Hexpl][Expl/Ring2][P@expl][C][\CH-expl][Branch1_3][Expl=Ring2][C][/B][P][\S][\C@Hexpl][=P@expl][Br+expl][=P][\S+expl][/O][/P][=S@@expl][N+expl][=P][/N][B-expl][=S][N@@+expl][Cexpl][\C@@Hexpl][/N][=N][Oexpl][\O][/C][/NHexpl][/S@expl][B-expl][S@@Hexpl][\S][C@@Hexpl][Sn+expl][SiH3expl][C][\B][S@@expl][Ring2][/C][P+expl][N][C][N][C][C][C][Branch2_3][=S+expl][BH2-expl][=Nexpl][#N][/C@@expl][Nexpl][CH-expl][/B][C][C][\N][S@@+expl][/P@expl][SnH4+2expl][Branch2_2][=P][/C@expl][/S+expl][S@Hexpl][\B][/C][N][Snexpl][BH3-expl][B-expl][\S][=S][N+expl][Sn+3expl][/I][\P][\S+expl][F][Cexpl][/S@expl][Siexpl][B@@-expl][/C@Hexpl][\Cl][/P@expl][O][O-expl][\C@@expl][C-expl][/O+expl][\O-expl][Branch1_3][N][/Cexpl][Expl\Ring1][B@-expl][O][N][SiH3expl][C][SnH6+3expl][=S@@expl][\S@expl][CH-expl][#N+expl][\S@@expl][/Cexpl][SnH4+2expl][=O][S@expl][O][\P][=Snexpl][Cexpl][C][/N+expl][P@@expl][/CH-expl][=IH2expl][N][=P@expl][#C][P@@Hexpl][P+expl][Br][=S@@expl][C-expl][/Br][=N+expl][P][=Siexpl][P][NHexpl][/Br][N+expl][\N+expl][N+expl][O][C][/C][\O-expl][=S@@expl][\S][BH-expl][Branch1_2][SnH2expl][Ring2][/CH-expl][=17Oexpl][\C@expl][=P@Hexpl][=P+expl][O][C][C][NHexpl][C][C][C][C][/P@@expl][N][B@@-expl][C+expl][=S][=P+expl][C][B][\I][=C][C][C][C][O][N][O][Branch2_1][SiH3expl][CHexpl][\S@@expl][/B][=P@Hexpl][Branch2_3][C@@Hexpl][/F][S@+expl][\N][/C][/B][Oexpl][P@@Hexpl][/NHexpl][/O][O][=SHexpl][\Oexpl][=Siexpl][P@+expl][SiH3expl][SnH6+3expl][O-expl][Branch1_2][CH2expl][\S@expl][=SHexpl][PHexpl][\F][\C@@Hexpl][O][C][O][Nexpl][O][C][N][Cl][N@@+expl][P@@Hexpl][O][C][/Cexpl][S@@expl][C][\O][\Br][/O][\N+expl][SHexpl][\Siexpl][=SHexpl][B@-expl][S][Br][\F][\S+expl][C][C][C][=N-expl][BH3-expl][#C-expl][/Cl][\S+expl][Expl=Ring2][CHexpl][C][Expl/Ring2][P@+expl][N-expl][#N][Br][\Snexpl][BH-expl][#C-expl][CH2expl][=Snexpl][/Cl][/P@expl][C][\Oexpl][Expl=Ring1]
```

However, after passing this SELFIES to sf.decoder() function, the output SMILES looks significantly shorter:
```
 C=[S@@]=[SH]=P/[S+]/[C@@H]/[P@@]\[Si]CCC/I
```

When I try to convert the SMILES back to SELFIES back again, I got different SELFIES:
```
[C][=S@@expl][=SHexpl][=P][/S+expl][/C@@Hexpl][/P@@expl][\Siexpl][C][C][C][/I]
```

Can I get some explanation why this happens? Thank you so much!

**Comment by MarioKrenn6240** [comment]
Hi Whentao-Shi,
I will check careful later, but for now i see that there is a `<sos>` symbol within the SELFIES string that is not part of SELFIES. How is it created?

best regards,
Mario

**Comment by Wentao-Shi** [comment]
Ah, It is my customized "start of sequence" token. I guess that is why the decoder function stops here. I think that is my implementation problem for this one. However, there are some other examples where there is no such illegal token:
```
[C][/N][Br][=P+expl][/B-expl][C@expl][Br+expl][S@+expl][C@expl][/C@expl][=O+expl][Br][I+expl][=Nexpl][/C@Hexpl][/C@expl][C][\Siexpl][C][IH2expl][Branch2_3][=B][=N-expl][/B][#C][=O+expl][\S@@expl][Branch2_1][\O-expl][/C@expl][\C@@expl][Branch2_1][=O+expl][=N][/CH-expl][Branch1_2][/O-expl][P@@expl][/S][C@expl][C][\C@expl][=S+expl][/C@@Hexpl][B-expl][\Cl][Expl\Ring2][/N+expl][\C@@Hexpl][B@@-expl][S@@+expl][Branch1_3][/F][#C][C][O][Expl=Ring2][\S@expl][C][C][Branch1_2][C][Oexpl][C@Hexpl][B@@-expl][\C-expl][P+expl][CH2-expl][=S@expl][=B][B-expl][SHexpl][C][O+expl][\I][P@expl][/C@@expl][P@Hexpl][N][C][C][B][P][\S@expl][P@@expl][Sn+2expl][Br+expl][\S@expl][C@expl][=N-expl][/B][=N+expl][/B-expl][\C@@expl][I+expl][\O][Oexpl][\Snexpl][C][C][C][=P][/CH-expl][C][C][C-expl][SH3expl][Branch1_3][Br][\C-expl][/N][/Cexpl][C][=S@@expl][C][N-expl][C][IH2expl][\Siexpl][Sn+3expl][C][N][S@@expl][=I][=S@+expl][P@expl][=O][/Br][#N][/P@@expl][=P][/C@@expl][\O-expl][Cl][/O][/S][B][N@@H+expl][Expl/Ring2][#C][I+expl][S@Hexpl][P@@Hexpl][/P@@expl][=N+expl][Sn+3expl][\C@expl][Branch1_2][/P@@expl][/C@expl][Br][\P][/I][\B][\O-expl][\C@expl]
```

The decoded SMILES is:
```
C/NBr
```

**Comment by MarioKrenn6240** [comment]
The reason here is that [Bromine](https://en.wikipedia.org/wiki/Bromine) is restricted to one bond, as it is in the halogen group, thus it is not possible to form the molecule you indend to describe (`'C/NBr=P'`).

RDKit also rejects that molecule:
`from rdkit import Chem
can_smiles = Chem.CanonSmiles('C/NBr=P')`

returns an error. SELFIES prevents the production of invalid molecules.

**Comment by Wentao-Shi** [comment]
I see. So the 100% validity of SELFIES is guaranteed by converting illegal SELFIES expression to the "closest" legal expression according to rules defined by SELFIES. Am I understanding this correctly?

**Comment by MarioKrenn6240** [comment]
Not really. The derivation can be understood as a [formal automaton](https://en.wikipedia.org/wiki/Automata_theory) (or equivalently [formal grammar](https://en.wikipedia.org/wiki/Formal_grammar)). The automaton starts in a state, and keeps the memory of possible bonds in its state. If the number is zero, the derivation reached its end and the produced state is returned (irrespectively whether there are more instructions in the instruction set, which are the input-SELFIES tockens).

Let's say, the automaton state is defined by **Xn**, where **n** stands for the number of possible bonds. In your case, for `C/NBr=P`, the automaton goes to state **X4** (`C`), then **X2** (`/N`), then at `Br` it goes to the end-of-derivation state.

**Comment by Wentao-Shi** [comment]
Thank you so much for the detailed explanation. Final question: is github the right place to raise questions about using SELFIES? I may come back in the future with other questions.

**Comment by MarioKrenn6240** [comment]
Yes, github is perfect for such questions, it might help others with similar questions. Please keep them coming.
