### ISSUE TITLE
Issue with decoding an encoded string.

### ISSUE THREAD

**Issue by Kohulan** [aspuru-guzik-group/selfies#44]
Hello @MarioKrenn6240 ,

While working on a few of our predicted results I came across a problem.

SELFIES version: 1.0.3

**1. for the molecule:https://pubchem.ncbi.nlm.nih.gov/compound/145735106**

- Canonical SMILES string: CI(C)I(C)I(C)C (from pubchem)
- SELFIES: [C][I][Branch1_1][C][C][I][Branch1_1][C][C][I][Branch1_1][C][C][C]
- Decoded SMILES: CI

**2. for the molecule:https://pubchem.ncbi.nlm.nih.gov/compound/145092330**

- Canonical SMILES string:FI(F)C1=CC=2NC(C)CN(C2C=C1C=3C=NN(C3)C)C (Generated using CDK)
- SELFIES: [F][I][Branch1_1][C][F][C][=C][C][N][C][Branch1_1][C][C][C][N][Branch2_1][Ring1][C][C][Expl=Ring1][Branch1_3][C][=C][Ring1][O][C][C][=N][N][Branch1_1][Ring2][C][Expl=Ring1][Branch1_1][C][C]
- Decoded SMIELS: FI

**3. for the molecule:https://pubchem.ncbi.nlm.nih.gov/compound/144364443**

Pubchem canonical SMILES

- Canonical SMILES string: CC1=CC=IOC2=C(CCCC3=C2C=CC(=C3)C)C=C1
- SELFIES: [C][C][=C][C][=I][O][C][=C][Branch1_1][P][C][C][C][C][=C][Ring1][Branch1_3][C][=C][C][Branch1_2][Ring2][=C][Ring1][Branch1_2][C][C][=C][Ring2][Ring1][Ring1]
- Decoded SMILES: CC=CCI

Canonical SMILES generated using CDK

- Canonical SMILES string: O1I=CC=C(C=CC2=C1C=3C=CC(=CC3CCC2)C)C
- SELFIES: '[O][I][=C][C][=C][Branch2_1][Ring1][Branch1_3][C][=C][C][=C][Ring1][Branch2_2][C][C][=C][C][Branch1_2][Branch2_3][=C][C][Expl=Ring1][Branch1_2][C][C][C][Ring1][O][C][C]'
- Decoded SMILES: OI

I quite didn't understand what is happening here. and I am not using any modifications to the code.

Another case:

SELFIES: [Cl][Cl][=C][C][C][=C][C][=C][C][=C][C][C][=C][C][Branch1_1][Ring2][C][Expl=Ring1][=C][=C][Ring1][=N][C][Ring1][O][Expl=Ring1][Branch1_3]
Decoded SMILES: ClCl

It seems to be a minor bug, maybe a fix would help us in our evaluations.

-Kohulan.R

**Comment by MarioKrenn6240** [comment]
Hi Kohulan,
Thanks a lot for these examples. They look like strange molecules involving [iodine](https://en.wikipedia.org/wiki/Iodine), which we didnt consider before. We will talk to our chemistry expert in the team how to fix in the most reasonable way.

For the moment: RDKit accepts iodine with up to five bonds. Using some more advanced settings, you can change manually the bond constraints, see [this example](https://github.com/aspuru-guzik-group/selfies/blob/master/examples/selfies_examples.ipynb), and [this part of our documentation](https://selfies.readthedocs.io/en/latest/selfies.html#advanced-functions).

Please see this code, which shows how to temporarily fix your issue:

```python
import selfies as sf
from rdkit import Chem

# The following four lines overwrite the standard constraints.
# Your three examples require that the bond restriction of iodine is relaxed.
# Let's follow RDKit's constraint and set the maximum bond to five.
default_constraints = sf.get_semantic_constraints()
new_constraints = default_constraints
new_constraints['I'] = 5  # Change the constraint of Iodine
sf.set_semantic_constraints(new_constraints)  # update constraints 


smiles1 = "CI(C)I(C)I(C)C"
smiles2 = "FI(F)C1=CC=2NC(C)CN(C2C=C1C=3C=NN(C3)C)C"
smiles3 = "CC1=CC=IOC2=C(CCCC3=C2C=CC(=C3)C)C=C1"

smiles=smiles1
encoded_selfies = sf.encoder(smiles)  # SMILES --> SEFLIES
decoded_smiles = sf.decoder(encoded_selfies)  # SELFIES --> SMILES

print(f"Original SMILES: {smiles}")
print(f"Translated SELFIES: {encoded_selfies}")
print(f"Translated SMILES: {decoded_smiles}")
print(f"== Equals: {smiles == decoded_smiles}")

# Recomended 
can_smiles = Chem.CanonSmiles(smiles)
print(can_smiles)

can_decoded_smiles = Chem.CanonSmiles(decoded_smiles)
print(f"RDKit Equals: {can_smiles == can_decoded_smiles}")
```

Please let me know whether that helps.

Thanks again,
Mario

**Comment by Kohulan** [comment]
Hello Mario,

Thanks a lot for the detailed example with the code. For now, this can solve the problem, But I don't think this can be a permanent solution. Since we are dealing with thousands of molecules changing the default constraint might affect other molecules which never had a problem decoding back in the first place. 

For the last case reported it is not even Iodine causing the problem. 

If the SELFIES decoder throws and error, I could handle such cases using a try and catch, since it doesn't throw any error handling them becomes a time-consuming process. 

So would be helpful if we can get a better bug fix.

Thank you :)

-Kohulan.R

**Comment by MarioKrenn6240** [comment]
If your SELFIES string have been translated from SMILES with the selfies.encoder, then this change of restriction will not influence at all any other SELFIES that have already been correctly translated. Actually, we will likely hardcode this change in version 1.0.4.

Actually, it is not a bug in the SELFIES code, but a domain restriction from chemistry that can be relaxed in some physical systems  (such as [periodate](https://en.wikipedia.org/wiki/Periodate)). We will have a full clarification in 1-2days. Thanks for bringing this up!

**Comment by MarioKrenn6240** [comment]
Hey Kohulan,
we have now fixed the issue. The problem was: your examples do not follow the standard [octet rules](https://en.wikipedia.org/wiki/Octet_rule), but use [hypervalences](https://en.wikipedia.org/wiki/Hypervalent_molecule). Hypervalences allow for additional molecules, but are much less understood than octet rules. Some of these molecules are well studied, for example [periodic acids](https://en.wikipedia.org/wiki/Periodic_acid) -- however many of those configurations are not yet, and its not known whether they are stable.

So in order to solve your issue, we kept the standard derivation fixed as it was before, but we added an option to the decoder that allows for derivation of molecules that are theoretically possible using hypervalences. Note however that RDKit does not accept all of those that might be theoretically possible (but which are not known yet).

In any way, if you want to use such molecules, use the following decoder (from [main page of github](https://github.com/aspuru-guzik-group/selfies#examples)):
```python
# More relaxed derivations to allow for hypervalences
# (Caution: Hypervalence rules are much less understood than octet rules.
# Some molecules containing hypervalences are important, generally it is not
# known which molecules are stable/reasonable).

hypervalence_selfies=sf.encoder('O=I(O)(O)(O)(O)O') #  orthoperiodic acid
standard_derived_smiles=sf.decoder(hypervalence_selfies)
# standard_derived_smiles -> 'OI', because octet rule for iodine allows for only one bond

relaxed_derived_smiles=sf.decoder(hypervalence_selfies,constraints='hypervalent')
# relaxed_derived_smiles -> 'O=I(O)(O)(O)(O)O', hypervalences allow for 7 bonds
```

Hope that helps.
Thanks for that issue, very nice one! :)

best regards,
Mario

**Comment by Kohulan** [comment]
Hi Mario,

This is great Thanks a lot to you and to the SELFIES team.

Now I could decode the problematic SELFIES. Since I depend on the SELFIES decoder to decode the predicted SELFIES it was a big problem. Now it is solved. It is really a quick fix. Thanks again.

Kind Regards,
Kohulan
