### ISSUE TITLE
Not using <sos> tokens?

### ISSUE THREAD

**Issue by JanoschMenke** [aspuru-guzik-group/selfies#47]
Hi,

I was going through the example and I found that you are not using any `<sos>` or `<eos>`  tokens to mark the beginning and end of a SELFIES.  At least I did not see them and maybe I just missed them. 
EDIT: As you are only using a RNN for Decoding I am asking more about the `<eos>` token.
 
I was wondering what the reasons were to decide against using the above mentioned tokes?

Greetings,
Janosch

**Comment by MarioKrenn6240** [comment]
I assume you talk about the example in `selfies/examples/vae_example/`.

We don't use nor need any start of string or end of string characters. If you look at this [subfunction of the `VAEDecoder`](https://github.com/aspuru-guzik-group/selfies/blob/16a489afa70882428bc194b2b24a2d33573f1651/examples/vae_example/chemistry_vae.py#L175), you can see that we decode  `sample_len` numbers.

Those numbers are then used to construct the the molecules in [sample_latent_space](https://github.com/aspuru-guzik-group/selfies/blob/16a489afa70882428bc194b2b24a2d33573f1651/examples/vae_example/chemistry_vae.py#L202). You can see that we use spaces for padding in [latent_space_quality](https://github.com/aspuru-guzik-group/selfies/blob/16a489afa70882428bc194b2b24a2d33573f1651/examples/vae_example/chemistry_vae.py#L214)

`molecule = molecule_pre.replace(' ', '')`

Please let us know whether this helps.

best regards,
Mario

**Comment by JanoschMenke** [comment]
Hi Mario, 

thanks for the quick answer. So I understand  (at least I think :) ) how the decoding takes place both for SMILES and for SELFIES and it also works without "start/end string" tokens

_Maybe I should rephrase my question: What reason speaks against using "start/end string" tokens. Shouldnt this elevate the models performance._ 

In my mind, the usage of those tokens might benefit smiles-based VAE more than selfies-based VAE because padding tokens in the middle of a smiles string have high risk of "breaking" the molecule. The additional tokens would make it easier for the model to learn the syntax of SMILE. While the syntax of Sefies need to be learned as well, it is far less complicated and removinng `[nop]` in the middle of a string will not result in invalid molecule.  I guess that is the point you are trying to make, but the lack of those tokens might be more unfavorable for the SMILES VAE.

This is just an idea I had as I was going through your code and could be completly wrong. I am by no means an expert in language models, nor SMILES and SELFIE Syntax. I am trying to getmore into working with string representation, and find your work super interesting 

Kind regards,
Janosch

**Comment by MarioKrenn6240** [comment]
Hi Janosch,
I understand your point, and I agree with it -- start&end tokens might help in specific ML applications such as VAE *one needs to test it, but i wouldnt be too surprised).

The reason we dont have it: SELFIES is considered a representation that is entirely independent of any application (we planned it as a model-independent approach). And as a representation, it is not necessary to have start/stop tokens, therefore I believe that adding it in the core encoder/decoder of SELFIES is not necessary.

However, I believe that it would make to test those in our VAE example, as a model-dependent adaptation (in a similar way, it should help SMILES strings). If you ever test whether adding those two model-dependent symbols in a VAE example, please let me know. Maybe you could then help merging this addition into the VAE example at the SELFIES github.

I hope this makes sense for you!

best regards,
Mario

**Comment by JanoschMenke** [comment]
Hey Mario, 

thanks for your reply and laying out the intention behind the expermimental choices. I can now see, the reasoning behind not using any additional tokens. At the moment I am a little short on time, but I do think it would be an interesting comparison to see how additional tokens influence the performance.

All the best,
Janosch
