### ISSUE TITLE
Dataset used for Fig. 4 in SELFIES paper

### ISSUE THREAD

**Issue by DannySalem** [aspuru-guzik-group/selfies#5]
In figure 4 of the SELFIES paper, you predict the logP solubility using the latent representation of a molecule. I would like to reproduce this type of result but I can't find a QM9 dataset with the logP target property.  The QM9 dataset in this repo only has the SMILES encoding of each molecule. Can you upload the QM9 dataset used to compare predicted and target logP properties?

**Comment by akshat998** [comment]
Hi, logP can be directly calculated from the rdKit Mol object. Here is an example from rdKit docs (https://www.rdkit.org/docs/GettingStartedInPython.html):

>>> from rdkit.Chem import Descriptors
>>> m = Chem.MolFromSmiles('c1ccccc1C(=O)O')
>>> Descriptors.MolLogP(m)
1.3848


Hope this answers your question. 
Regards,
