### ISSUE TITLE
Irritation with 'selfies_to_encoding' and 'encoding_to_selfies' dictionary

### ISSUE THREAD

**Issue by NiklasHoelter** [aspuru-guzik-group/selfies#51]
Hi everyone,

i just wanted to draw attention to some irriation/minor bug when using the `selfies_to_encoding` and `encoding_to_selfies` function for integer tokenization of SELFIES.

I followed the instructions in your "Integer and one-hot encoding SELFIES" paragraph and created the `vocab_stoi` with shape `{token: int}` as you mentioned:

```
tokens = sf.get_alphabet_from_selfies(selfies)
vocab_stoi = {token: i for i,token in enumerate(tokens)}
```

With this dict, the `selfies_to_encoding` function works fine but however, the `encoding_to_selfies` function raises a KeyError because it expects a dict with shape `{int: token}` as i've seen in your code. An easy workaround would be the creation of a second dict with swapped keys and values like:

`self.vocab_itos = dict((v,k) for k,v in self.vocab_stoi.items())`

But however, i thought it would be nice to use the same vocab for tokenization and detokenization and avoid irritations concerning that functions. Thank you in advance!

**Comment by alstonlo** [comment]
Hi Niklas, 

Thank you for your feedback and suggestions! I understand that it would be more convenient to use the same vocab. However, the reason why `encoding_to_selfies` expects the reverse vocab (i.e.`{int: token}`) is to avoid having to internally reverse the forward vocab (i.e. `{token: int}`) every time the method is called. This would be inefficient if `encoding_to_selfies` is called many times or with a large alphabet. 

The intended use of the method is to invert the `{token: int}` vocab once, as you have written, and then pass the reversed vocab to the method each time. Please let me know if this answers your questions, thanks!

**Comment by NiklasHoelter** [comment]
Hi and thank for your explanation.

This makes absolutely sense, i just have not thought about that from that perspektive. Thanks again!
