### ISSUE TITLE
Functions for Quotient Graph and SELFIES

### ISSUE THREAD

**Issue by SamCox822** [aspuru-guzik-group/selfies#63]
We'd like to add a couple of functions to go between quotient graphs and SELFIES, building on the selfies.kekulize module. This would be included in a shared qgraph.py file.

The functions we would like to add are:
- qg_encoder -> Converts SELFIES string (input) into a quotient graph (output)
- qg_decoder -> Converts quotient graph (input) into a SELFIES string (output)

This is applicable to crystal structures, which are not represented as molecular graphs. In reference to the crystal structure Discord, a crystal is represented as an infinite periodic graph (see https://application.wiley-vch.de/books/sample/3527409394_c01.pdf). The infinte periodic graph has a translation action, and, when factored out, results in the quotient (or fundamental finite) graph. (See the derivation here: https://link.springer.com/content/pdf/10.1007/s11537-012-1144-4.pdf) Quotient graphs are desirable for crystals because they can represent (by nodes and edges) the infinite periodic graphs in a finite graph, while perserving connectivity.

**Comment by MarioKrenn6240** [comment]
Hi Sam,
Thanks a lot for your message. I just went through the write-up of the QG at discord yesterday and understand better what you have in mind now. It would be great to have those two functions, where we have SELFIES representing QGs. We can certainly add such overlay functions to the whole repo. Best would be to have them build outside first, and then think about how to include precisely.

Are you planning to work on it, or have you actually worked on it already? v2.0 (which is in its final days before release) will likely restructure the whole code, and make it slightly more connected to adjacency matrices.

**Comment by SamCox822** [comment]
Great, thank you for the feedback. 

I will work off of v2.0 to build the functions. I also saw the mol_graph.py file, and I will incorporate that as into the functions as well.

**Comment by SamCox822** [comment]
We will actually need to use labelled quotient graphs to uniquely represent a crystal structure, adding the complexity of including edge direction and edge labels. I think that we can just introduce new tokens to represent the edge directions. We can use + and ~ to represent an edge from A-->B and B-->A, respectively.

In a labelled quotient graph, each edge has a translation vector label, signifying which direction the next "cell" is in. These translation vectors are of the form uvw, which can be any combination of -1,0,-1. This is important when a quotient graph has self-loops and parallel edges, as well as when distinguishing between different lattice structures with the same unlabelled quotient graph.

I think that we can use these 3-value strings directly if we add a token to signify the start. We can use the ! symbol. For example, [C][!0-10][...]

Putting this all together, we can represent a directed edge X-->... with translation vector 110 as: [X][!+110]...

**Comment by SamCox822** [comment]
@MarioKrenn6240 I am closing this issue. My research direction has changed, and this is no longer relevant.
