### ISSUE TITLE
Generative model are producing invalid molecules with SELFIES?

### ISSUE THREAD

**Issue by HelloJocelynLu** [aspuru-guzik-group/selfies#65]
Hi, I love the idea of using SELFIES instead of SMILES for higher robustness. So recently I am working on a generative model that generating SELFIES instead of SMILES. However, I still got some predicted SELFIES that lead to invalid molecules (cannot parsed by rdkit, i.e., Chem.MolFromSmiles() returns `None`). I also observed that all molecules contain 'B' (Boron). Did I miss anything?
SELFIES version: 1.0.1
rdkit version: 2021.03.1
I used `selfies.decoder()` to convert SELFIES to SMILES.
Attached are some example molecules.
Many thanks!
[FailedMolecules.csv](https://github.com/aspuru-guzik-group/selfies/files/7312614/FailedMolecules.csv)

**Comment by MarioKrenn6240** [comment]
Thank you @HelloJocelynLu - i can confirm that there seems to be a problem, even with the latest `SELFIES 1.0.4`. Will come back to you shortly. We are creating the `SELFIES 2.0.0` version RN, so just in time to fix this very soon.

Thanks and best regards,
Mario

**Comment by HelloJocelynLu** [comment]
> OK, a quick investigates shows that your `B` uses 4 valence bonds while RDKit only allows for 3. We are investigating whether we can easily restrict them in general, or whether we need to consider some subtleties.
> 
> For now, you could use manually modify the constraint list:
> 
> ```
> from rdkit.Chem import MolFromSmiles, MolToSmiles
> import selfies as sf
> 
> current_selfies='[C][C][Branch1_1][C][C][O][B][Branch2_1][Branch1_1][Branch1_2][C][=C][C][=C][C][Branch1_2][Ring2][=C][Ring1][Branch1_2][C][=C][C][=C][C][=C][Ring1][Branch1_2][N][Ring1][Branch2_3][C][=C][C][=C][C][=C][C][=C][C][=C][Ring1][Branch1_2][C][=C][C][=C][C][=C][Ring1][Branch1_2][C][Ring1][=C][=C][Ring2][Ring1][C][O][C][Ring2][Ring2][C][Branch1_1][Ring2][C][C][C]'
> 
> strSMILES=sf.decoder(current_selfies)
> print(strSMILES)
> 
> new_constraints = sf.get_semantic_constraints() # Get default list
> new_constraints['B'] = 3 # Add constraint for Boron
> sf.set_semantic_constraints(new_constraints) # Store it
> 
> strSMILES=sf.decoder(current_selfies) # This one gives the constraint (and correct) result
> print(strSMILES)
> 
> rr=MolToSmiles(MolFromSmiles(strSMILES),kekuleSmiles=True)
> ```
> 
> (more infos [here](https://github.com/aspuru-guzik-group/selfies/blob/master/examples/selfies_examples.ipynb) )
> 
> Thanks a lot! Mario

Thanks Mario. It works like a charm!
