### ISSUE TITLE
SELFIES tokens list

### ISSUE THREAD

**Issue by Kohulan** [aspuru-guzik-group/selfies#68]
Hi @MarioKrenn6240 ,

Would it be possible to publish the old list of SELFIES tokens and the tokens which replaces them in the new SELFIES version?

Since STOUT and DECIMER uses a set of tokens when using machine learning models they are failing with the new SELFIES 2.0 due to token issue. Having the list of tokens I could check them and replace them.

-Kohulan

**Comment by MarioKrenn6240** [comment]
Hi @Kohulan,
Thanks for your question, sorry that the update brakes your tools. We hope this was the last necessary not-backwards compatible update.

We describe it in the [CHANGELOG ](https://github.com/aspuru-guzik-group/selfies/blob/master/CHANGELOG.md)in some detail, what is most interesting for you might be these:

> Updated the syntax of SELFIES symbols to be cleaner and more readable.
> 
>     Removing expl from atomic symbols, e.g., [C@@Hexpl] becommes [C@@H]
>     Cleaner branch symbols, e.g., [BranchL_2] becomes [=BranchL]
>     Cleaner ring symbols, e.g., [Expl=RingL] becomes [=RingL]
>     If you want to use the old symbols, use the compatible=True flag to selfies.decoder, e.g., sf.decoder('[C][C][Expl=Ring1]',compatible=True) (not recommended!)

What might also help you is the following function that takes care of the `compatible=True` flag: [modernize_symbol(symbol)](https://github.com/aspuru-guzik-group/selfies/blob/3b44777794cbd1a4a9f3816a5995ce95122a97e0/selfies/compatibility.py#L4).

Does this already help you, or do you need something more specific?

best regards,
Mario

**Comment by Kohulan** [comment]
Dear @MarioKrenn6240 ,

Thank you for the detailed description. It would be much helpful if you could publish the whole list of original SELFIES tokens and the SELFIES tokens which replaces them in the new version may be a comparison table here would be much helpful.

Would it be possible?

Kind regards,
Kohulan

**Comment by alstonlo** [comment]
Hi @Kohulan, 

While it is easy to convert original SELFIES symbols to their replacements (through the `modernize_symbol` function), it would be very difficult to enumerate over all possible SELFIES tokens. If you have a specific subset of symbols you are interested in, I can generate the replacement table! For now I have generated the table for some select tokens: 
```
Old                New
[C]                [C]
[Cexpl]            [CH0]
[13Cexpl]          [13C]
[C@@Hexpl]         [C@@H1]
[C@Hexpl]          [C@H1]
[C@@expl]          [C@@]
[C@expl]           [C@]
[CHexpl]           [CH1]
[CH4expl]          [CH4]
[C+1expl]          [C+1]
[C-1expl]          [C-1]
[C+expl]           [C+1]
[C-expl]           [C-1]
[Branch1_1]        [Branch1]
[Branch1_2]        [=Branch1]
[Branch1_3]        [#Branch1]
[Ring1]            [Ring1]
[Expl=Ring1]       [=Ring1]
[Expl#Ring1]       [#Ring1]
```

As a brief explanation, the updates for branch and ring symbols can be succinctly described in these [lines of code](https://github.com/aspuru-guzik-group/selfies/blob/master/selfies/compatibility.py#L33). For old atom symbols, we removed their `expl` portion. In addition, we fixed charges and explicit hydrogens to one representation in these symbols (`+/-X` and `HX` respectively). That is, symbols like `[Fe++expl]` and `[CHexpl]` become `[Fe+2]` and `[CH1]`.   

Please let me know if this is what you are looking for. Thanks!

**Comment by Kohulan** [comment]
Hello @alstonlo ,

Thank you for the reply. Can you kindly provide the new SELFIES tokens for the following?

```
[C] , [=C] , [Branch1_1] , [Branch1_2] , [Ring1] , [N] , [O] , [=O] , [=N] , [Ring2] , [Branch2_1] , [S] , [Branch1_3] , [F] 
[Branch2_2] , [Cl] , [Branch2_3] , [Br] , [#C] , [/C] , [#N] , [P] , [C@Hexpl] , [C@@Hexpl] , [=N+expl] , [=S] , [=N-expl]
[I] , [O-expl] , [N+expl] , [\\C] , [/N] , [/O] , [C@expl] , [B] , [C@@expl] , [\\N] , [Expl/Ring1] , [\\O] , [NH+expl] , [I-expl]
[Expl\\Ring1] , [P+expl] , [NH2+expl] , [/Cl] , [/S] , [NH3+expl] , [Cl-expl] , [/F] , [#N+expl] , [C-expl] , [\\S] , [N-expl]
[=NH+expl] , [=I] , [S-expl] , [\\Cl] , [S+expl] , [#C-expl] , [B-expl] , [/Br]
```

For now, this would be better for me, In future, I would adapt to the new version of SELFIES so things would be much easier overall.

Kind regards,
Kohulan

**Comment by alstonlo** [comment]
Hi @Kohulan,

Please find attached the [update_table](https://github.com/aspuru-guzik-group/selfies/files/7470301/update_table.txt) for your listed symbols. Thanks!

**Comment by alstonlo** [comment]
Sorry, my mistake, I accidentally closed this issue!

**Comment by Kohulan** [comment]
Hi @alstonlo ,

Thanks a lot for this. It is very much helpful.

Kind regards,
Kohulan
