### ISSUE TITLE
To get SELFIES characters of specific substructure

### ISSUE THREAD

**Issue by SejeongPark8354** [aspuru-guzik-group/selfies#70]
First of all, thank you for your wonderful research about molecule representation. 

While using selfies, I have one question regarding utilization of SELFIES. 
Is there any method which can extract exact locations of specific substructure among whole SELFIES characters of molecule? 
I tried to do this by manually checking result after removing some characters, but I couldn't get the result I want. 

I would be very grateful if you could give me an answer.
Thanks, 
Sejeong.

**Comment by robpollice** [comment]
I think this can be done for SMILES using RDKit. Check for instance section "Substructure Searching": https://www.rdkit.org/docs/GettingStartedInPython.html
At least that gives the numbering and that can be mapped onto the SMILES string. When you have the SMILES string mapping, it should be relatively straightforward to convert it into a SELFIES mapping.

**Comment by SejeongPark8354** [comment]
@robpollice Thank you for your fast response. Oh, I see. I'll try the method you suggest. I hadn't thought of that idea which use SMILES string mapping to get a SELFIES mapping. Thanks again.

**Comment by SejeongPark8354** [comment]
I have one more question. I removed some alphabet of the specific selfies, and I realized that whole selfies alphabets are connected to make one whole molecule. For example, just one [Ring1] removal can change whole molecule structure. 
Therefore, I thought that to get molecule with only one substructural change from original molecule can not be done by one selfies alphabet change. Is it right? 
Your answer will be helpful for me to use SELFIES easily. 
Thanks!!

**Comment by robpollice** [comment]
While it is true that a single change can result in a very different structure, this can still be used to obtain substructures. Statistically, if you perform random changes, a large portion of the resulting molecules will only have a substructural change. The only thing you need to do is filter by molecualr similarity. For more details, read our work in this regard here: https://pubs.rsc.org/en/content/articlelanding/2021/SC/D1SC00231G
The corresponding implementation can be found here: https://github.com/aspuru-guzik-group/stoned-selfies

**Comment by SejeongPark8354** [comment]
@robpollice Thank you for your kind response. I already tried STONED. 
I will try again to get molecules with substructural change which I want.
