### ISSUE TITLE
SELFIE encoding fails with PF6- or hypervalent Phosphorus

### ISSUE THREAD

**Issue by bananenpampe** [aspuru-guzik-group/selfies#73]
Hello everyone,

please find below an example of the transformation of a SMILES of the PF6- anion to a SELFIES.
This transformation does not respect stoichiometry.
Could you advise what I am doing wrong, or if there is a possible workaround?

```python
fail_smiles = "F[P-](F)(F)(F)(F)F"

hypervalent_sf = sf.encoder(fail_smiles, strict=False)  
#is '[F][P-1][Branch1][C][F][Branch1][C][F][Branch1][C][F][Branch1][C][F][F]'

standard_derived_smi = sf.decoder(hypervalent_sf)

sf.set_semantic_constraints("hypervalent")
sf.decoder(hypervalent_sf) # is 'F[P-1](F)(F)CF'

```

**Comment by MarioKrenn6240** [comment]
Hi @bananenpampe,
Thanks for your interest, and question.

Indeed the default constraints on phosphorus are too strong for your example, and we did not relax the constraint for phospherus in the [hypervalence constraints](https://github.com/aspuru-guzik-group/selfies/blob/0c161ce420c9ecfd3ae36cade30956767821df64/selfies/bond_constraints.py#L26). We are discussing now whether we should.

For now, there is a simple workaround, by using custom constraints (see [tutorial for more details](https://selfiesv2.readthedocs.io/en/latest/tutorial.html#Customizing-SELFIES)):
```python
import selfies as sf


fail_smiles = "F[P-](F)(F)(F)(F)F"
print(fail_smiles)


hypervalent_sf = sf.encoder(fail_smiles, strict=False)  

smiles_default = sf.decoder(hypervalent_sf)
print(smiles_default) # is 'F[P-1](F)(F)CF'

new_constraints = sf.get_preset_constraints("default")
new_constraints['P-1'] = 7
# potentially also useful:
# new_constraints['P'] = 6
# new_constraints['P+1'] = 5
sf.set_semantic_constraints(new_constraints)

smiles_custom=sf.decoder(hypervalent_sf) # is 'F[P-1](F)(F)(F)(F)F'

print(smiles_custom)
```

best regards,
Mario

**Comment by bananenpampe** [comment]
Dear Mario,

thanks a lot for your comment! That helped indeed.
Just as a quick comment, maybe you should also consider changing `hypervalent_constraints['?'] ` to a larger value. e.g. metallocenes like ferrocene (valence 10) are quite common in chemical reactions.

**Comment by MarioKrenn6240** [comment]
Glad my comment helped. Thanks for the good suggestion. We will discuss this internally.
