### ISSUE TITLE
how to reduce invalidity due to aromatic constraints without de-aromatize molecules

### ISSUE THREAD

**Issue by qwerthjkl45** [aspuru-guzik-group/selfies#8]
When I try to generate the molecules, this message,  _Can't kekulize mol.  Unkekulized atoms_, keeps jumping out. Is there any way to solve this problem without de-aromatize molecules?

**Comment by akshat998** [comment]
Hi, 
Some clarification & expansion on the problem would be great!. At which step is this message being generated? :) 
Regards,
Akshat 
Co-author of SELFIES

**Comment by qwerthjkl45** [comment]
Hi, 
Thanks for the immediate response and sorry for the short problem description. 
Below is the procedure I've done. 
1. First, I used the SELFIES alphabet( I added more alphabets in the original selfies_alphabet list, such as [c],  [o], etc.) to generate molecules. 
2. Use the decoder in the SELFIES package to decode the output from the previous step to SMILES string. 
3. Check if the molecules are valid by using RDKit's function (Chem.MolFromSmiles(smiles_str). This is the step that a warning message shows up. 
![warning_message](https://user-images.githubusercontent.com/17170163/78736527-f36c7400-797f-11ea-82ea-8ff000ba420d.png)
(The first line is the warning message and the second line is smiles string and its corresponding SELFIES string.)


And my problem here is that is there any way to generate aromatic molecules and at the same time keeping high validity?


Thanks for your help again! 
Regards,
Ann

**Comment by MarioKrenn6240** [comment]
Hi Ann,
SELFIES can work with aromatic symbols, if they are not mutated. If you mutate them, they could lead to semantic mistakes.

However, aromatic symbols are just short-form notation, and can be written without loss of generality (in most, if not all, cases) in SMILES without aromatic (lowercase) symbols. For that, we have used [Molconverter](https://docs.chemaxon.com/display/docs/Molecule_file_conversion_with_Molconverter.html) to **de-aromatize** the molecules, via the instruction

```
molconvert smiles:-a_huckel_ex "smiles_code" > out
```

It is likely that aromatic symbols can even be handled directly within SELFIES, by encoding Kekulization rules into formal grammar rules of SELFIES. As mentioned in the conclusion of our paper, we plan to perform a workshop (after all is back to normal) where we will discuss further developments (such as those mentioned in your question) and standardisations of SELFIES. Feel free to join if you are interested! We will provide details at a later point.

best regards,
Mario

**Comment by qwerthjkl45** [comment]
Hi Mario,

Thanks for your help and clear explanation. I'll try to use Molconverter. 
Looking forward to your workshop and hoping everything gets back to normal soon.  

Best Regards,
Ann

**Comment by MarioKrenn6240** [comment]
SELFIES 1.0.0 supports aromatic rings now on the fly.
