### ISSUE TITLE
Comprehensive Vocabulary

### ISSUE THREAD

**Issue by keshavd** [aspuru-guzik-group/selfies#80]
Is it possible to get a comprehensive vocabulary of the SELFIES language?

**Comment by MarioKrenn6240** [comment]
hi @keshavd, thanks for your interest. we have a functuon called `selfies.get_semantic_robust_alphabet`, is that what you are searching for?

**Comment by keshavd** [comment]
The robust alphabet does not contain some of the "words" I come across when converting some of my SMILES to SELFIES. These include:

```
[N@@+1]
[\\C@@]
[\\C@]
[C@@H1]
[\\Br]
[\\C@H1] 
[=NH2+1]
[13CH3]
```
and more.

Do you have any recommendations on how I can retrieve a complete vocabulary of what "words" might make up the SELFIES language?

Currently, I am updating the my vocabulary every time I translate a new SMILES string.

**Comment by MarioKrenn6240** [comment]
You can expand the `selfies.get_semantic_robust_alphabet()` function by all isotope numbers (i.e. any number infront of atoms), all chiral tags (every `@` or `@@`) all prefixes (`-`, `=`, `#`, `\\` and `/`), all charges (`+-N` after atom). [This part of the code](https://github.com/aspuru-guzik-group/selfies/blob/fdb17890097a77989b17a4f3434538b1d8aa18cb/selfies/grammar_rules.py#L106) might be useful. We discussed what we add into the function, for usability, we kept it as it is (most people migth not need those additional infos)

**Comment by keshavd** [comment]
This is perfect. Thank you!
