### ISSUE TITLE
Generate molecule string from atom properties

### ISSUE THREAD

**Issue by dgm2** [aspuru-guzik-group/selfies#82]
Hello

is there a way with selfies to generate/synthesise a valid molecule string from a set of properties?
like atom type, hybridization, number of hydrogen bonds?
or generate molecular string given a set of parameters that one can sample?

Thanks

**Comment by akshat998** [comment]
Hi Guame, 

You might benefit from checking out our STONED-SELFIES work: 
paper: https://pubs.rsc.org/en/content/articlelanding/2021/SC/D1SC00231G
repo: https://github.com/aspuru-guzik-group/stoned-selfies

Regards
Akshat

**Comment by MarioKrenn6240** [comment]
Dear @giame,
What you are asking for are not functional properties but structural properties. Therefore, a suitable sampling method from a suitable set of Atom-tokens will be enough. For example, if you want to create a molecule that consists only of carbon, oxygen and nitrogen, then just combine `[C]`, `[=C]`, `[#C]`, `[N]`,  `[=N]`, `[O]`,  `[=O]`, together with `[Ring1]` and `[Branch1]`.

SELFIES itself does not provide costumate macro functions, it is a lowlevel representation directly useable by other codes. If you are interested in certain functionalities, then more complex applications such as STONED suggested by Akshat is what you should look for.

Hope that helps!
Mario
