### ISSUE TITLE
Update for  index table documentation needed ??

### ISSUE THREAD

**Issue by EtienneReboul** [aspuru-guzik-group/selfies#83]
Hello , 
I am trying to improve on the stoned selfies  mutation protocol by  comprehensively splitting the SELFIES into the "main" chain and the different branches and rings. 
However, I think the current index table in the documentation is for a depreciated  version of Selfies: https://selfies.readthedocs.io/en/latest/tutorial.html#index-symbols
![image](https://user-images.githubusercontent.com/45311890/166078678-bd887cd2-48f4-4411-9b1e-47f44f165dca.png)

Is there a function that i can call to give me the index table like the selfies.get_semantic_robust_alphabet() for the alphabet ? 

Thank you in advance

**Comment by MarioKrenn6240** [comment]
Hi @EtienneReboul - Yes we are aware that the documentation is outdated. We are preparing a much more detailed document right now. In the meantime, you could have a look at our [perspective paper](https://arxiv.org/abs/2204.00056), and see Table I.

best regards,
Mario

**Comment by EtienneReboul** [comment]
Hello @MarioKrenn6240 , thank you for your reply. Very pleased to hear that the documentation will be updated soon. 

Best regards, 
Etienne
