### ISSUE TITLE
Clarify Python Version

### ISSUE THREAD

**Issue by whitead** [aspuru-guzik-group/selfies#85]
Related to my discussion in #84, there are inconsistent versions of Python for selfies:

* `setup.py` says 3.5-3.8
* `tox` tests only 3.6
* CI env is 3.7

I would propose targeting all currently supported version of Python (3.7-3.10). Python 3.6 reached end of support last year and, for example, `numpy` dropped support for 3.6 in `v1.20.0` (2021). We should also align the versions in `tox` and `setup.py` to test stated versions.

**Comment by MarioKrenn6240** [comment]
I agree with your proposal (especially given numpy dropped the support too, and as its end-of-lifecycle and wont get any security updates anymore), we should be consistent and go for python 3.7+. Could you or @alstonlo help updating the `tox` and `setup.py` please?

**Comment by whitead** [comment]
Addressed in #86
