### ISSUE TITLE
[=Branch1] vs [Branch1] ? 

### ISSUE THREAD

**Issue by EtienneReboul** [aspuru-guzik-group/selfies#88]
Hello,
 I am working on improving the stoned-selfies protocol and i was wondering why sometimes  the selfies.encoder chooses to use the token [=Branch1] instead of [Branch1]. 

If we take the celecoxibs:
SMILES= 'CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(=O)(=O)N)C(F)(F)F' 
=> SELFIES= '[C][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][=C][C][=Branch2][Ring1][#Branch1][=N][N][Ring1][Branch1][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1]**[S][=Branch1][C][=O][=Branch1][C][=O]**[N]**[C][Branch1][C][F][Branch1][C][F]**[F]'

Is there a  new particular rules for selfies 2.0 for branches and rings? I did not find it in the follow up paper: "SELFIES and the future of molecular string representations"

Thanks you in advance , 
Etienne Reboul

**Comment by MarioKrenn6240** [comment]
Hi @EtienneReboul , thanks for your interest.

Sorry the documentation of 2.0 is a bit scattered. It is explained in the CHANGELOG for 2.0 (which we fix in few weeks).

We use now, for easier reading [=Branch1] instead of [Branch1_2] (style of v0.x and v1.x).

Does that help?
