### ISSUE TITLE
Can I convert the SELFIES to 3D molecular geometry?

### ISSUE THREAD

**Issue by DiracMD** [aspuru-guzik-group/selfies#90]
I read the manual find it no information about the convertion between SELFIES pattern and 3D molecular geometry.

**Comment by MarioKrenn6240** [comment]
SELFIES is a representation for molecular graphs. You can use other methods to create 3d structures of the translated molecular graph. Direct translation to 3d structures, i.e. storing of the spatial coordinates of the individual atoms, is not possible within SELFIES.
