### ISSUE TITLE
Appearance of P and S in SELFIES representation for molecules that do not contain P or S.

### ISSUE THREAD

**Issue by R-applet** [aspuru-guzik-group/selfies#91]
I converted ~40k SMILES strings that originated from the CSD into SELFIES. I noticed that ~8k had SELFIES that contained either P or S (which I assume mean Phosphorous and Sulfur). However, these molecules do not contain and P or S atoms according to SMILES or molecular formula. I show an example below.
Sample code:
smi = 'COC(=O)c1ccc(cc1)C1=NOC(=C1C(=O)c1ccccc1)c1ccc2OCOc2c1'
mol = Chem.MolFromSmiles(smi)
formula = CalcMolFormula(mol)
self = sf.encoder(smi)

print('SMILES - ',smi)
print('Formula - ',formula)
print('SELFIES - ',self)

Returns:
SMILES -  COC(=O)c1ccc(cc1)C1=NOC(=C1C(=O)c1ccccc1)c1ccc2OCOc2c1
Formula -  C25H17NO6
SELFIES -  [C][O][C][Branch1_2][C][=O][C][=C][C][=C][Branch1_1][Branch1_1][C][=C][Ring1][Branch1_2][C][=N][O][C][Branch1_2]**[S]**[=C][Ring1][Branch1_1][C][Branch1_2][C][=O][C][=C][C][=C][C][=C][Ring1][Branch1_2][C][=C][C][=C][O][C][O][C][Ring1][Branch1_1][=C][Ring1][Branch2_2]

Here you can see the **[S]** character in bold in the SELFIES.

Is this an issue or do I not understand how SELFIES work?

**Comment by whitead** [comment]
Hi @R-applet! SELFIES re-uses tokens for marking branch and ring sizes. What you're seeing here is `[S]` being used to indicate the branch size, not as an indicator of presence of a sulfur atom.

**Comment by R-applet** [comment]
Ah I see thank you.
