### ISSUE TITLE
Encoding disconnected compounds

### ISSUE THREAD

**Issue by RoryGarlandGlam** [aspuru-guzik-group/selfies#92]
I am currently trying to tokenize disconnect compounds and I am getting a key error. 

- python3.8
- selfies 2.1.0

```python3
import selfies as sf
smiles_dataset = ["CN(CC1=CC=CC=C1)C2=C(C=C(C=C2)NS(=O)(=O)C3=CC=CS3)C(=O)O.C(=O)(C(F)(F)F)O", "CCC(CC)(CN)NC(=O)CC1=C2C=CC=CC2=NN1.Cl"]
selfies_dataset = list(map(sf.encoder, smiles_dataset))
alphabet = sf.get_alphabet_from_selfies(selfies_dataset)
alphabet.add("[nop]")
vocab_stoi = {symbol: idx for idx, symbol in enumerate(alphabet)}
label, one_hot = sf.selfies_to_encoding(selfies_dataset[0], vocab_stoi, pad_to_len=128)
```

Which returns a key error:

```python3
Traceback (most recent call last):
  File "tokenizer_generator.py", line 238, in <module>
    label, one_hot = sf.selfies_to_encoding(selfies_dataset[0], vocab_stoi, pad_to_len=128)
  File "/Users/rorygarland/Library/Caches/pypoetry/virtualenvs/smiles-l_Axq8W4-py3.8/lib/python3.8/site-packages/selfies/utils/encoding_utils.py", line 51, in selfies_to_encoding
    integer_encoded = [vocab_stoi[char] for char in char_list]
  File "/Users/rorygarland/Library/Caches/pypoetry/virtualenvs/smiles-l_Axq8W4-py3.8/lib/python3.8/site-packages/selfies/utils/encoding_utils.py", line 51, in <listcomp>
    integer_encoded = [vocab_stoi[char] for char in char_list]
KeyError: '.'
```

I also tried using the get_semantic_robust_alphabet()

```python3
vocab_stoi = {symbol: idx for idx, symbol in enumerate(sf.get_semantic_robust_alphabet())}
label, one_hot = sf.selfies_to_encoding(selfies_dataset[0], vocab_stoi, pad_to_len=128)
```

Which returns the exact same issue.

I also checked out previous issues i.e. #6 but it looks like certain api's, i.e. selfies_alphabet(), have been removed so I cannot recreate the solution. I also considered the solution in #80 but it feels like '.' is something which should be recognised. What is the best way to solve this?

A possible solution is just to manually append the key to the dict ala

```python3
vocab_stoi['.'] = len(vocab_stoi)
```

**Comment by MarioKrenn6240** [comment]
Hi @RoryGarlandGlam !
We did not implement disconnected structures via `[.]` because this notation is misused sometimes, for example for plotting [Ferrocene](https://en.wikipedia.org/wiki/Ferrocene). However it should be very simple for you to use SELFIES anyway. Just split your SMILES string by the `.` symbol, and add each substring independently to the SELFIES encoder.

Hope that helps,
Mario

**Comment by MarioKrenn6240** [comment]
Hi @RoryGarlandGlam,
Thanks for your interest. Yes, `[.]` is not returned by `sf.get_alphabet_from_selfies(selfies_dataset)` as a token, as it gives unexpected behavior if its in the alphabet. After all, this symbol just indicates that the string should be split at this very location (except of some cases where the `.`-symbol is misused to help representing for instance [Ferrocene](https://en.wikipedia.org/wiki/Ferrocene).

If you insist to use `'.'`, then you can indeed use (with a little fix): `vocab_stoi['[.]'] = len(vocab_stoi)`

Hope that help,
Mario

**Comment by RoryGarlandGlam** [comment]
This is great, thank you so much for the reply Mario! 👍

**Comment by zhoubay** [comment]
> Hi @RoryGarlandGlam, Thanks for your interest. Yes, `[.]` is not returned by `sf.get_alphabet_from_selfies(selfies_dataset)` as a token, as it gives unexpected behavior if its in the alphabet. After all, this symbol just indicates that the string should be split at this very location (except of some cases where the `.`-symbol is misused to help representing for instance [Ferrocene](https://en.wikipedia.org/wiki/Ferrocene).
> 
> If you insist to use `'.'`, then you can indeed use (with a little fix): `vocab_stoi['[.]'] = len(vocab_stoi)`
> 
> Hope that help, Mario

I found this a little trouble, since `[.]` is not the token, yet `.` is. So in this senario, `vocab_stoi['[.]'] = len(vocab_stoi)` might not work, `vocab_stoi['.'] = len(vocab_stoi)` works, in my opinion.

**Comment by pabloacera** [comment]
Hi, I had the same issue trying to use selfies.selfies_to_encoding with a common chemo drug cisplatin which is encoded like '[N].[N].[Cl][Pt][Cl]' Is there any difference between using `vocab_stoi['[.]'] = len(vocab_stoi)` and `vocab_stoi['.'] = len(vocab_stoi)` It is not clear whether the behaviour will be different, if I am using the same set of molecules.

**Comment by alstonlo** [comment]
I agree that the correct fix is to add the symbol `"."` (and not `"[.]"`) to the vocabulary! The `sf.selfies_to_encoding()` utility tokenizes SELFIES strings using `sf.split_selfies()` ([docs](https://selfiesv2.readthedocs.io/en/latest/selfies.html#selfies.split_selfies)), which treats `"."` as a individual token.
