### ISSUE TITLE
Question about getting attribution for rings?

### ISSUE THREAD

**Issue by dfossl** [aspuru-guzik-group/selfies#94]
Sorry if this is a trivial question but in the README.md it mentions that using `get_attribution` can provide a finer few of the attributions for SELFIE -> SMILE. As far as I can see `get_attribution` is a method of the MolecularGraph class and the decoder doesn't have any flag or option to return the MolecularGraph Object. Is there another method that I am missing that does construct the MolecularGraph?

**Comment by whitead** [comment]
Hi @dfossl! That comment was more for developers that are trying to do something new with the library. Is there a specific example you can share that you're having trouble interpreting with the attribution?

**Comment by dfossl** [comment]
@whitead Thanks for prompt reply! That make sense. No trouble actually I just noticed that statement in the README and wanted to make sure I wasn't missing something. But with that context it makes sense👍
