### ISSUE TITLE
Nano particle selfies

### ISSUE THREAD

**Issue by jessielyons** [aspuru-guzik-group/selfies#95]
Dear authors,

Can you please guide me if I can use SELFIES for nano particles? Also how does SELFIES relate to quasi-Smiles representation?

Any guidance will be really helpful. Thanks so much!

Cheers,
Jessie

**Comment by MarioKrenn6240** [comment]
I cannot help there and i have not heart of quasi-smiles representation, but maybe @whitead can jump in?

**Comment by whitead** [comment]
Quasi-SMILES looks a lot like CXSMILES. You can take a look a that, which is supported in standard tools like rdkit.

Not sure what your goal is, but you can represent the nanoparticle with something like [Au] and set-up a rule for its valence. However, SELFIES only captures atoms/bonds. If you have other properties, you should consider a different representation.

**Comment by whitead** [comment]
A recent paper on SMILES for composite compounds like nanoparticles: https://pubs.acs.org/doi/10.1021/acs.jcim.2c00690

**Comment by jessielyons** [comment]
Hi all, thank you for your responses. Sorry I didn't clarify that I am only interested in *lipid* nanoparticles and siRNA.

1. First, how do you suggest we can use SELFIS especially for lipid nanoparticles?
2. Second, can all SMILES extracted from Drug Bank be converted into SELFIS?
3. Do you recommend if selfis can be used for siRNA for which "canonical smiles" are available?

I am asking these questions as based on my review of your publications and lectures. I understood that all smiles can be converted into selfis and that selfis is much better representation than smiles. Apologies for all the confusion I may have created.

Thanks again, Jessie
