### ISSUE TITLE
SELFIES to SMILES decoding not reversible

### ISSUE THREAD

**Issue by anoushka2000** [aspuru-guzik-group/selfies#96]
Dear authors,
 Can you please explain why the direct conversion (sf.encoder(sf.decoder(valid_selfies[i])) raises an error in some cases? Do the decoded smiles need to be canonicalize before being encoded to SELFIES?

```
import selfies
from rdkit import Chem
import pandas as pd

valid_selfies = pd.read_csv("smiles_selfies_error.csv").valid_selfies
for i in [0, 1, 3]:
    smiles = sf.decoder(valid_selfies[i])
    print(f"Decoded to SMILES: {smiles}")
    try:
        # This doesn't work
        back_to_selfies = sf.encoder(smiles, strict=False)
    except Exception as e:
        print(e)
        # But this works
        back_to_selfies = sf.encoder(
Chem.MolToSmiles(Chem.MolFromSmiles(smiles)))
```
[smiles_selfies_error.csv](https://github.com/aspuru-guzik-group/selfies/files/10429206/smiles_selfies_error.csv)

**Comment by MarioKrenn6240** [comment]
Thanks for your comment. Can you provide the concrete string which doesnt work please?

**Comment by anoushka2000** [comment]
For example:
`[#Branch1][#Branch2][#C][#Branch2][#Branch1][=O][#Branch2][C@@H1][=N][C@@H1].[/O][/N][-\Ring2][=N+1][=Branch2][=O][=Branch2][/H][#Branch1][H][=Ring1].[/C@@][/C@@][#Branch2][=Branch1].[#Branch2][\H][#Branch1][#N][C][-\Ring2][#Branch1][=N+1][#Branch2].[=O][/H][#Branch2][-\Ring2][=N+1][#Branch1][N][-\Ring2][=Branch1][#Branch2][=N+1][N@@H1+1][=N+1].[-\Ring2][-\Ring2][/C][/C][=O][/C][#C][CH1+1][#Branch1]`  and `[=N+1][C-1][/C][/C@@][#Branch2][#C][=C][/C@@][C@][=C].[#N][/C][N@H1+1][/O][/C@@][=Ring1][#Branch1][#C][P][#Branch2][H][#Branch1][=N+1][/C@@][C@][/H][#N][#Branch1][=N+1][Branch1][/N][#Branch2][/C][#Branch1][H][#Branch2].[/N][/C][=O][=Ring2][Branch2][=Branch1][=O][#N][/C][C@@][/H][#Branch2][/O][/H][/H][#Branch1][/C][/N][C@H1][=Branch1][C@@H1][/H][/C@@]`

**Comment by MarioKrenn6240** [comment]
Can you provide the SMILES code please? That will be useful, as your problematic encoding& decoding starts with SMILES. Thanks.

**Comment by MarioKrenn6240** [comment]
OP did not clarify issues in a reproducible way.
