### ISSUE TITLE
Questions about SELFIES Syntax

### ISSUE THREAD

**Issue by hanm19** [aspuru-guzik-group/selfies#98]
Hello everybody, 

I am looking to understand how to read the SELFIES code for molecules with lots of rings and branches. I am a chemistry master's student hoping to incorporate SELFIES into my future projects, but coding is a relatively new concept for both me and my lab group. 

I was wondering if I could be referred to someone who might be able to help me with understanding how to read the code? I understand the basics but I get confused with slightly more complex molecules. Even just a 30min meeting online would be extremely helpful

Thanks in advance.

**Comment by alstonlo** [comment]
Hello and sorry for the delay! 

To clarify, are you asking for help with understanding the SELFIES framework or the `selfies` source code (or both)?  If it is the former, our recent preprint (https://arxiv.org/abs/2302.03620) details the underlying algorithms and may be helpful. I would also be happy to set up an online meeting (my email is [alston.lo@mail.utoronto.ca](mailto:alston.lo@mail.utoronto.ca))!
