### ISSUE TITLE
"input violates the currently-set semantic constraints" for RDKit-valid SMILES

### ISSUE THREAD

**Issue by isty2e** [aspuru-guzik-group/selfies#99]
I am experiencing potentail discrepancies between the default parser and RDKit when working with certain SMILES strings. Specifically, SMILES strings that are RDKit-sanitizable cause errors when attempting to encode them, resulting in `N with 5 bond(s) - a max. of 3 bond(s) was specified` errors. Even when using `strict=False`, the original molecule is not always restored when decoded back to SMILES.

However, I have discovered a potential workaround in #96: by rotating and canonicalizing the original SMILES string with `Chem.MolToSmiles(Chem.MolFromSmiles(smiles))`, the encoding issue seems to be resolved.

To reproduce this issue and solution, I have included a simple Jupyter notebook code:

```python
from rdkit import Chem
from IPython.display import SVG
from rdkit.Chem.Draw import rdMolDraw2D
import selfies as sf


def draw_mol(mol):
    molSize = (250, 250)
    mc = Chem.Mol(mol.ToBinary())

    drawer = rdMolDraw2D.MolDraw2DSVG(molSize[0], molSize[1])

    drawer.DrawMolecule(mc)
    drawer.FinishDrawing()
    # get the SVG string
    svg = drawer.GetDrawingText()
    # fix the svg string and display it
    display(SVG(svg.replace('svg:','')))


smiles = "C1(C(OCC)=O)=C(CCC)OC(=C(C#N)C1C1C=CC=C(C=1)N(=O)=O)N"
# smiles = "C1(NC(=O)C(CC)OC(=O)/C=C/C2=CC=C(C=C2)N(=O)=O)SC2=C(CCCC2)C=1C(OCC)=O"
mol = Chem.MolFromSmiles(smiles)
mol2 = Chem.MolFromSmiles(sf.decoder(sf.encoder(smiles, strict=False)))
mol3 = Chem.MolFromSmiles(
    sf.decoder(sf.encoder(Chem.MolToSmiles(Chem.MolFromSmiles(smiles))))
)

draw_mol(mol)
draw_mol(mol2)
draw_mol(mol3)
```

**Comment by robpollice** [comment]
The SMILES you are trying to process requires the hypervalent constraints of SELFIES. The following code produces three equivalent images in my hands:
`from rdkit import Chem
from IPython.display import SVG
from rdkit.Chem.Draw import rdMolDraw2D
import selfies as sf


def draw_mol(mol):
    molSize = (250, 250)
    mc = Chem.Mol(mol.ToBinary())

    drawer = rdMolDraw2D.MolDraw2DSVG(molSize[0], molSize[1])

    drawer.DrawMolecule(mc)
    drawer.FinishDrawing()
    # get the SVG string
    svg = drawer.GetDrawingText()
    # fix the svg string and display it
    display(SVG(svg.replace('svg:','')))


smiles = "C1(C(OCC)=O)=C(CCC)OC(=C(C#N)C1C1C=CC=C(C=1)N(=O)=O)N"
constraints_hypervalent = sf.get_preset_constraints("hypervalent")
sf.set_semantic_constraints(constraints_hypervalent)
# smiles = "C1(NC(=O)C(CC)OC(=O)/C=C/C2=CC=C(C=C2)N(=O)=O)SC2=C(CCCC2)C=1C(OCC)=O"
mol = Chem.MolFromSmiles(smiles)
mol2 = Chem.MolFromSmiles(sf.decoder(sf.encoder(smiles, strict=False)))
mol3 = Chem.MolFromSmiles(
    sf.decoder(sf.encoder(Chem.MolToSmiles(Chem.MolFromSmiles(smiles))))
)

draw_mol(mol)
draw_mol(mol2)
draw_mol(mol3)`

**Comment by robpollice** [comment]
The SMILES you are trying to process requires the hypervalent constraints. The following code produces three equivalent images in my hands:
```python
from rdkit import Chem
from IPython.display import SVG
from rdkit.Chem.Draw import rdMolDraw2D
import selfies as sf


def draw_mol(mol):
    molSize = (250, 250)
    mc = Chem.Mol(mol.ToBinary())

    drawer = rdMolDraw2D.MolDraw2DSVG(molSize[0], molSize[1])

    drawer.DrawMolecule(mc)
    drawer.FinishDrawing()
    # get the SVG string
    svg = drawer.GetDrawingText()
    # fix the svg string and display it
    display(SVG(svg.replace('svg:','')))


smiles = "C1(C(OCC)=O)=C(CCC)OC(=C(C#N)C1C1C=CC=C(C=1)N(=O)=O)N"
constraints_hypervalent = sf.get_preset_constraints("hypervalent")
sf.set_semantic_constraints(constraints_hypervalent)
# smiles = "C1(NC(=O)C(CC)OC(=O)/C=C/C2=CC=C(C=C2)N(=O)=O)SC2=C(CCCC2)C=1C(OCC)=O"
mol = Chem.MolFromSmiles(smiles)
mol2 = Chem.MolFromSmiles(sf.decoder(sf.encoder(smiles, strict=False)))
mol3 = Chem.MolFromSmiles(
    sf.decoder(sf.encoder(Chem.MolToSmiles(Chem.MolFromSmiles(smiles))))
)

draw_mol(mol)
draw_mol(mol2)
draw_mol(mol3)
```

**Comment by isty2e** [comment]
Hm, if hypervalence is required, I wonder why the default constraints works without any problem after canonicalization. I haven't delved into details, but could it be that the charge assignment to the nitrogen atom is somehow rotation-dependent?

**Comment by robpollice** [comment]
After canonicalization, the nitrogen has 4 instead of 5 bonds and is assigned a partial positive charge. Simply print the SMILES string after canonicalization and observe the differences between the initial and the final SMILES strings.
